/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CardType 
type CardType string

// List of CardType
const (
	CARDTYPE_CREDIT CardType = "Credit"
	CARDTYPE_DEBIT CardType = "Debit"
	CARDTYPE_CHARGE CardType = "Charge"
	CARDTYPE_OTHER CardType = "Other"
	CARDTYPE_PREPAID CardType = "Prepaid"
	CARDTYPE_VISA_DEFERRED_DEBIT CardType = "VisaDeferredDebit"
	CARDTYPE_NETWORK_ONLY CardType = "NetworkOnly"
)
