/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PaymentMethods 
type PaymentMethods string

// List of PaymentMethods
const (
	PAYMENTMETHODS_APPLE_PAY PaymentMethods = "ApplePay"
	PAYMENTMETHODS_GOOGLE_PAY PaymentMethods = "GooglePay"
	PAYMENTMETHODS_CREDIT_CARD PaymentMethods = "CreditCard"
	PAYMENTMETHODS_PAYSAFE_ISSUED_CARD_ID PaymentMethods = "PaysafeIssuedCardID"
)
