/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TransactionInfo struct for TransactionInfo
type TransactionInfo struct {
	TransactionId string `json:"TransactionId,omitempty"` 
	TransactionType TransactionType `json:"TransactionType"` 
	TransactionStatus TransactionStatus `json:"TransactionStatus"` 
}
