/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CardBrand 
type CardBrand string

// List of CardBrand
const (
	CARDBRAND_MASTERCARD CardBrand = "Mastercard"
	CARDBRAND_VISA CardBrand = "Visa"
	CARDBRAND_AMERICAN_EXPRESS CardBrand = "AmericanExpress"
	CARDBRAND_MAESTRO CardBrand = "Maestro"
	CARDBRAND_JCB CardBrand = "JCB"
	CARDBRAND_CUP CardBrand = "CUP"
	CARDBRAND_DISCOVER CardBrand = "Discover"
	CARDBRAND_OTHER CardBrand = "Other"
)
