/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FeesTypes 
type FeesTypes string

// List of FeesTypes
const (
	FEESTYPES_CHARGE_FEE FeesTypes = "ChargeFee"
	FEESTYPES_CHARGE_FEE_FIXED FeesTypes = "ChargeFeeFixed"
	FEESTYPES_CHARGE_FEE_VARIABLE FeesTypes = "ChargeFeeVariable"
	FEESTYPES_MONTHLY_FEE FeesTypes = "MonthlyFee"
	FEESTYPES_REVENUE_SHARE FeesTypes = "RevenueShare"
)
