/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// ExtendedInstallmentPlanAllOf struct for ExtendedInstallmentPlanAllOf
type ExtendedInstallmentPlanAllOf struct {
	BusinessUnit *BuRef `json:"BusinessUnit,omitempty"`
	ShopperPaymentRequestTime *SplititTime `json:"ShopperPaymentRequestTime,omitempty"`
}
