/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FundingRuleDataScpProviderSettingAllOf struct for FundingRuleDataScpProviderSettingAllOf
type FundingRuleDataScpProviderSettingAllOf struct {
	Id int64 `json:"Id"` 
	ScpProviderId int64 `json:"ScpProviderId"` 
	FundingRuleDataId int64 `json:"FundingRuleDataId"` 
	CreditLine float64 `json:"CreditLine"` 
	EffectiveScpRevenueSharePercent float64 `json:"EffectiveScpRevenueSharePercent"` 
	EffectiveScpVariableCostApr float64 `json:"EffectiveScpVariableCostApr"` 
	IsSecondary bool `json:"IsSecondary"` 
	RotationWeight float64 `json:"RotationWeight"` 
	IsEnabled bool `json:"IsEnabled"` 
}
