/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// MerchantAccountType 
type MerchantAccountType string

// List of MerchantAccountType
const (
	MERCHANTACCOUNTTYPE_NONE MerchantAccountType = "None"
	MERCHANTACCOUNTTYPE_DEFAULT MerchantAccountType = "Default"
)
