/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PaymentFormMessage struct for PaymentFormMessage
type PaymentFormMessage struct {
	Type *PaymentFormMessageType `json:"Type"`
	Code int32 `json:"Code"`
	Message string `json:"Message,omitempty"`
	IsEmpty bool `json:"IsEmpty"`
}
