/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanDateInfo struct for InstallmentPlanDateInfo
type InstallmentPlanDateInfo struct {
	InstallmentsPlanDateType InstallmentsPlanDateType `json:"InstallmentsPlanDateType"` 
	StartDate string `json:"StartDate,omitempty"` 
	EndDate string `json:"EndDate,omitempty"` 
	AllDates bool `json:"AllDates"` 
}
