/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// AgentFeeType 
type AgentFeeType string

// List of AgentFeeType
const (
	AGENTFEETYPE_FLAT_FEE AgentFeeType = "FlatFee"
	AGENTFEETYPE_BUY_RATE AgentFeeType = "BuyRate"
)
