/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PisMemberPasswordHistoriesAllOf struct for PisMemberPasswordHistoriesAllOf
type PisMemberPasswordHistoriesAllOf struct {
	PisMemberId int64 `json:"PisMemberId"` 
	PisMember *PisMembers `json:"PisMember,omitempty"` 
}
