/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// BinData struct for BinData
type BinData struct {
	BinNumber string `json:"BinNumber,omitempty"` 
	CardBrand CardBrand `json:"CardBrand"` 
	IssuingCountryIsoNumber string `json:"IssuingCountryIsoNumber,omitempty"` 
	CardType CardType `json:"CardType"` 
	IsPrepaid bool `json:"IsPrepaid"` 
	CardClass string `json:"CardClass,omitempty"` 
	ProductId string `json:"ProductId,omitempty"` 
	IssuerBankName string `json:"IssuerBankName,omitempty"` 
}
