/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// Countries struct for Countries
type Countries struct {
	Id int64 `json:"Id"` 
	IsoName string `json:"IsoName,omitempty"` 
	IsoNumber int32 `json:"IsoNumber"` 
	IsoA2 string `json:"IsoA2,omitempty"` 
	IsoA3 string `json:"IsoA3,omitempty"` 
	Continent string `json:"Continent,omitempty"` 
	UtcTimeOffsetInMins int32 `json:"UtcTimeOffsetInMins"` 
	IsZipUsed bool `json:"IsZipUsed,omitempty"` 
	BinDataItems []BinDataItems `json:"BinDataItems,omitempty"` 
	CountrySubdivisions []CountrySubdivisions `json:"CountrySubdivisions,omitempty"` 
	TerminalCountries []TerminalCountries `json:"TerminalCountries,omitempty"` 
	CurrencyCountries []CurrencyCountries `json:"CurrencyCountries,omitempty"` 
}
