/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// TokensAllOf struct for TokensAllOf
type TokensAllOf struct {
	Token string `json:"Token,omitempty"` 
	ValidTill *SplititTime `json:"ValidTill,omitempty"` 
	LastUsage *SplititTime `json:"LastUsage,omitempty"` 
	ParameterGroupId int64 `json:"ParameterGroupId,omitempty"` 
	Type string `json:"Type,omitempty"` 
	ParameterGroup *ParameterGroups `json:"ParameterGroup,omitempty"` 
	UserId int64 `json:"UserId"` 
	UserType UserType `json:"UserType"` 
	InstallmentPlanId int64 `json:"InstallmentPlanId,omitempty"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
}
