/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RefundLogEntries struct for RefundLogEntries
type RefundLogEntries struct {
	Id int64 `json:"Id"` 
	Amount float64 `json:"Amount"` 
	InstallmentPlanId int64 `json:"InstallmentPlanId"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
}
