/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// LearnMoreDetailsRequest struct for LearnMoreDetailsRequest
type LearnMoreDetailsRequest struct {
	Amount *MoneyWithCurrencyCode `json:"Amount,omitempty"`
	NumberOfInstallments int32 `json:"NumberOfInstallments,omitempty"`
}
