/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// AccountUpdaterProvider 
type AccountUpdaterProvider string

// List of AccountUpdaterProvider
const (
	ACCOUNTUPDATERPROVIDER_FIRST_DATA AccountUpdaterProvider = "FirstData"
	ACCOUNTUPDATERPROVIDER_OPTIMAL_PAYMENTS AccountUpdaterProvider = "OptimalPayments"
)
