/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ParametersAllOf struct for ParametersAllOf
type ParametersAllOf struct {
	Key string `json:"Key,omitempty"` 
	Value string `json:"Value,omitempty"` 
	ParameterGroupId int64 `json:"ParameterGroupId"` 
	ParameterGroup *ParameterGroups `json:"ParameterGroup,omitempty"` 
}
