/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// MerchantVertical 
type MerchantVertical string

// List of MerchantVertical
const (
	MERCHANTVERTICAL_NOT_SET MerchantVertical = "NotSet"
	MERCHANTVERTICAL_COMMUNICATION MerchantVertical = "Communication"
	MERCHANTVERTICAL_HEALTH_BEAUTY MerchantVertical = "HealthBeauty"
	MERCHANTVERTICAL_JEWELLERY MerchantVertical = "Jewellery"
	MERCHANTVERTICAL_AUTO MerchantVertical = "Auto"
	MERCHANTVERTICAL_OFFICE_SUPPLIES MerchantVertical = "OfficeSupplies"
	MERCHANTVERTICAL_ELECTRONICS MerchantVertical = "Electronics"
	MERCHANTVERTICAL_TRAVEL MerchantVertical = "Travel"
	MERCHANTVERTICAL_APPAREL_ACCESSORIES MerchantVertical = "ApparelAccessories"
	MERCHANTVERTICAL_HARDWARE_HOME_IMPROVEMENT MerchantVertical = "HardwareHomeImprovement"
	MERCHANTVERTICAL_SPECIALITY MerchantVertical = "Speciality"
	MERCHANTVERTICAL_MEDICAL_HEALTH MerchantVertical = "MedicalHealth"
	MERCHANTVERTICAL_SPORTING_GOODS MerchantVertical = "SportingGoods"
	MERCHANTVERTICAL_HOUSEWARE_HOMEFURNISHINGS MerchantVertical = "Houseware_Homefurnishings"
)
