/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// OnBoardingMethod 
type OnBoardingMethod string

// List of OnBoardingMethod
const (
	ONBOARDINGMETHOD_SELF OnBoardingMethod = "Self"
	ONBOARDINGMETHOD_DIRECT OnBoardingMethod = "Direct"
	ONBOARDINGMETHOD_DEVELOPER OnBoardingMethod = "Developer"
)
