/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// Keks struct for Keks
type Keks struct {
	Id int64 `json:"Id"` 
	Cards []Cards `json:"Cards,omitempty"` 
	Key string `json:"Key,omitempty"` 
	Version int32 `json:"Version"` 
}
