/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentsPlanDateType 
type InstallmentsPlanDateType string

// List of InstallmentsPlanDateType
const (
	INSTALLMENTSPLANDATETYPE_NONE InstallmentsPlanDateType = "None"
	INSTALLMENTSPLANDATETYPE_LAST_CHARGE_DATE InstallmentsPlanDateType = "LastChargeDate"
	INSTALLMENTSPLANDATETYPE_RESERVE_RETURN_DATE InstallmentsPlanDateType = "ReserveReturnDate"
	INSTALLMENTSPLANDATETYPE_CREATED_DATE InstallmentsPlanDateType = "CreatedDate"
	INSTALLMENTSPLANDATETYPE_FINANCED_DATE InstallmentsPlanDateType = "FinancedDate"
	INSTALLMENTSPLANDATETYPE_SHIPPING_DATE InstallmentsPlanDateType = "ShippingDate"
	INSTALLMENTSPLANDATETYPE_PROCESSING_DATE InstallmentsPlanDateType = "ProcessingDate"
)
