/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ScpProvidersCurrencies struct for ScpProvidersCurrencies
type ScpProvidersCurrencies struct {
	ScpProviderId int64 `json:"ScpProviderId"` 
	CurrencyId int64 `json:"CurrencyId"` 
	Currency *Currencies `json:"Currency,omitempty"` 
	ScpProviders *ScpProviders `json:"ScpProviders,omitempty"` 
}
