/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CardStateLogsAllOf struct for CardStateLogsAllOf
type CardStateLogsAllOf struct {
	CardId int64 `json:"CardId"` 
	ExpirationMonth int32 `json:"ExpirationMonth"` 
	ExpirationYear int32 `json:"ExpirationYear"` 
	CardHolderName string `json:"CardHolderName,omitempty"` 
	AddressDataAddressLine string `json:"AddressDataAddressLine,omitempty"` 
	AddressDataZip string `json:"AddressDataZip,omitempty"` 
	Version int32 `json:"Version"` 
	IsVerified bool `json:"IsVerified"` 
	ChangeSource string `json:"ChangeSource,omitempty"` 
	AddressDataAddressLine2 string `json:"AddressDataAddressLine2,omitempty"` 
	AddressDataCity string `json:"AddressDataCity,omitempty"` 
	AddressDataCountryId int64 `json:"AddressDataCountryId,omitempty"` 
	AddressDataStateId int64 `json:"AddressDataStateId,omitempty"` 
	AddressDataLegacyFullAddressLine string `json:"AddressDataLegacyFullAddressLine,omitempty"` 
	Card *Cards `json:"Card,omitempty"` 
	Country *Countries `json:"Country,omitempty"` 
	State *CountrySubdivisions `json:"State,omitempty"` 
	Installments []Installments `json:"Installments,omitempty"` 
	ReAuthorizations []ReAuthorizations `json:"ReAuthorizations,omitempty"` 
	AddressData *AddressData2 `json:"AddressData,omitempty"` 
}
