/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RefundPlanRequest struct for RefundPlanRequest
type RefundPlanRequest struct {
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"`
	Amount *MoneyWithCurrencyCode `json:"Amount,omitempty"`
	RefundStrategy *RefundStrategy `json:"RefundStrategy,omitempty"`
}
