/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RangeType 
type RangeType string

// List of RangeType
const (
	RANGETYPE_MERCHANT_TRANSACTION_VOLUME RangeType = "MerchantTransactionVolume"
	RANGETYPE_PLAN_INSTALLMENT_COUNT RangeType = "PlanInstallmentCount"
)
