/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// AuthenticationType 
type AuthenticationType string

// List of AuthenticationType
const (
	AUTHENTICATIONTYPE_SPLITIT_SESSION AuthenticationType = "SplititSession"
	AUTHENTICATIONTYPE_CAPTCHA AuthenticationType = "Captcha"
)
