/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CountryState struct for CountryState
type CountryState struct {
	Country string `json:"Country,omitempty"` 
	State string `json:"State,omitempty"` 
}
