/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FeeRateCollections struct for FeeRateCollections
type FeeRateCollections struct {
	Id int64 `json:"Id"` 
	RangeType RangeType `json:"RangeType"` 
	FeeRates []FeeRates `json:"FeeRates,omitempty"` 
}
