/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// SystemTextCategory 
type SystemTextCategory string

// List of SystemTextCategory
const (
	SYSTEMTEXTCATEGORY_TERMS_AND_CONDITIONS SystemTextCategory = "TermsAndConditions"
	SYSTEMTEXTCATEGORY_EMAIL_CONTENT SystemTextCategory = "EmailContent"
	SYSTEMTEXTCATEGORY_ERROR SystemTextCategory = "Error"
	SYSTEMTEXTCATEGORY_EMAIL_TEMPLATE SystemTextCategory = "EmailTemplate"
	SYSTEMTEXTCATEGORY_ADMINISTRATION_POTRAL SystemTextCategory = "AdministrationPotral"
	SYSTEMTEXTCATEGORY_RECEIPT SystemTextCategory = "Receipt"
	SYSTEMTEXTCATEGORY_INSTALLMENT_PLAN_STATUS SystemTextCategory = "InstallmentPlanStatus"
	SYSTEMTEXTCATEGORY_INSTALLMENT_STATUS SystemTextCategory = "InstallmentStatus"
	SYSTEMTEXTCATEGORY_PURCHASE_METHOD SystemTextCategory = "PurchaseMethod"
	SYSTEMTEXTCATEGORY_OPERATION_TYPE SystemTextCategory = "OperationType"
	SYSTEMTEXTCATEGORY_CARD_BRAND SystemTextCategory = "CardBrand"
	SYSTEMTEXTCATEGORY_PAYMENT_DETAILS SystemTextCategory = "PaymentDetails"
	SYSTEMTEXTCATEGORY_COMMON SystemTextCategory = "Common"
	SYSTEMTEXTCATEGORY_V_POS SystemTextCategory = "VPos"
	SYSTEMTEXTCATEGORY_PAYMENT_TRANSACTION_SHOPPER_MESSAGE SystemTextCategory = "PaymentTransactionShopperMessage"
	SYSTEMTEXTCATEGORY_TERMS_AND_CONDITIONS_LEGAL SystemTextCategory = "TermsAndConditionsLegal"
	SYSTEMTEXTCATEGORY_ECOMM SystemTextCategory = "Ecomm"
	SYSTEMTEXTCATEGORY_SHOPPER_SPLITIT_ACCOUNT SystemTextCategory = "ShopperSplititAccount"
	SYSTEMTEXTCATEGORY_SMS_CONTENT SystemTextCategory = "SMSContent"
	SYSTEMTEXTCATEGORY_POS SystemTextCategory = "POS"
	SYSTEMTEXTCATEGORY_FLEX_FIELDS SystemTextCategory = "FlexFields"
	SYSTEMTEXTCATEGORY_MESSAGING_SYSTEM SystemTextCategory = "MessagingSystem"
	SYSTEMTEXTCATEGORY_PAYMENT_FORM_V3 SystemTextCategory = "PaymentFormV3"
	SYSTEMTEXTCATEGORY_HOW_SPLITIT_WORKS SystemTextCategory = "HowSplititWorks"
	SYSTEMTEXTCATEGORY_UPSTREAM_MESSAGING SystemTextCategory = "UpstreamMessaging"
	SYSTEMTEXTCATEGORY_ONBOARDING SystemTextCategory = "Onboarding"
)
