/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ZipAddressDetailsAllOf struct for ZipAddressDetailsAllOf
type ZipAddressDetailsAllOf struct {
	CountrySubdivisionId int64 `json:"CountrySubdivisionId"` 
	Zip string `json:"Zip,omitempty"` 
	CountrySubdivision *CountrySubdivisions `json:"CountrySubdivision,omitempty"` 
}
