/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RefundStrategy 
type RefundStrategy string

// List of RefundStrategy
const (
	REFUNDSTRATEGY_FUTURE_INSTALLMENTS_FIRST RefundStrategy = "FutureInstallmentsFirst"
	REFUNDSTRATEGY_FUTURE_INSTALLMENTS_LAST RefundStrategy = "FutureInstallmentsLast"
	REFUNDSTRATEGY_FUTURE_INSTALLMENTS_NOT_ALLOWED RefundStrategy = "FutureInstallmentsNotAllowed"
)
