/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PaymentGatewayTransactionLogs struct for PaymentGatewayTransactionLogs
type PaymentGatewayTransactionLogs struct {
	Id int64 `json:"Id"` 
	AvsMessageMessageCode string `json:"AvsMessageMessageCode,omitempty"` 
	AvsMessageMessageText string `json:"AvsMessageMessageText,omitempty"` 
	CvvMessageMessageCode string `json:"CvvMessageMessageCode,omitempty"` 
	CvvMessageMessageText string `json:"CvvMessageMessageText,omitempty"` 
	ExpiryDateMessageMessageCode string `json:"ExpiryDateMessageMessageCode,omitempty"` 
	ExpiryDateMessageMessageText string `json:"ExpiryDateMessageMessageText,omitempty"` 
	ResultMessageMessageCode string `json:"ResultMessageMessageCode,omitempty"` 
	ResultMessageMessageText string `json:"ResultMessageMessageText,omitempty"` 
	Result bool `json:"Result"` 
	TransactionId string `json:"TransactionId,omitempty"` 
	CompleteResponseXml string `json:"CompleteResponseXml,omitempty"` 
	AdditionalData string `json:"AdditionalData,omitempty"` 
	RequestedCurrencyCode string `json:"RequestedCurrencyCode,omitempty"` 
	TerminalGatewayDataId int64 `json:"TerminalGatewayDataId"` 
	ReferencePaymentGatewayTransactionLogId int64 `json:"ReferencePaymentGatewayTransactionLogId,omitempty"` 
	ProcessedAmountAmount float64 `json:"ProcessedAmountAmount"` 
	RequestedAmountAmount float64 `json:"RequestedAmountAmount"` 
	InstallmentPlanId int64 `json:"InstallmentPlanId,omitempty"` 
	IsChargeback bool `json:"IsChargeback"` 
	IsAsync bool `json:"IsAsync,omitempty"` 
	TransferId string `json:"TransferId,omitempty"` 
	ReferencePaymentGatewayTransactionLog *PaymentGatewayTransactionLogs `json:"ReferencePaymentGatewayTransactionLog,omitempty"` 
	TerminalGatewayData *TerminalGatewayDatas `json:"TerminalGatewayData,omitempty"` 
	FraudDetectionLogs []FraudDetectionLogs `json:"FraudDetectionLogs,omitempty"` 
	InstallmentPaymentGatewayTransactionLogs []InstallmentPaymentGatewayTransactionLogs `json:"InstallmentPaymentGatewayTransactionLogs,omitempty"` 
	InverseReferencePaymentGatewayTransactionLog []PaymentGatewayTransactionLogs `json:"InverseReferencePaymentGatewayTransactionLog,omitempty"` 
	PaymentGatewayTransactionAsyncLogs []PaymentGatewayTransactionAsyncLogs `json:"PaymentGatewayTransactionAsyncLogs,omitempty"` 
	ReAuthorizationPaymentGatewayTransactionLogs []ReAuthorizationPaymentGatewayTransactionLogs `json:"ReAuthorizationPaymentGatewayTransactionLogs,omitempty"` 
	PublicId string `json:"PublicId,omitempty"` 
	TraceId string `json:"TraceId,omitempty"` 
	Type OperationType `json:"Type"` 
	AvsMessage *PaymentGatewayMessage `json:"AvsMessage,omitempty"` 
	CvvMessage *PaymentGatewayMessage `json:"CvvMessage,omitempty"` 
	ExpiryDateMessage *PaymentGatewayMessage `json:"ExpiryDateMessage,omitempty"` 
	ResultMessage *PaymentGatewayMessage `json:"ResultMessage,omitempty"` 
	ProcessedAmount *Money2 `json:"ProcessedAmount,omitempty"` 
	RequestedAmount *Money2 `json:"RequestedAmount,omitempty"` 
}
