/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// Currencies struct for Currencies
type Currencies struct {
	Id int64 `json:"Id"` 
	CurrencyCode string `json:"CurrencyCode"` 
	CurrencyName string `json:"CurrencyName"` 
	CurrencySymbol string `json:"CurrencySymbol"` 
	CurrencyIsoNumber string `json:"CurrencyIsoNumber"` 
	DecimalPlaces int32 `json:"DecimalPlaces"` 
}
