/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TerminalCountries struct for TerminalCountries
type TerminalCountries struct {
	CountryId int64 `json:"CountryId"` 
	Country *Countries `json:"Country,omitempty"` 
}
