/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PaymentGatewayTransactionAsyncLogs struct for PaymentGatewayTransactionAsyncLogs
type PaymentGatewayTransactionAsyncLogs struct {
	Id int64 `json:"Id"` 
	Result bool `json:"Result"` 
	ManualVerification bool `json:"ManualVerification"` 
	ResponseLog string `json:"ResponseLog,omitempty"` 
	ReferenceGatewayTransactionId string `json:"ReferenceGatewayTransactionId,omitempty"` 
	ReferencePaymentGatewayTransactionLogId int64 `json:"ReferencePaymentGatewayTransactionLogId,omitempty"` 
	ReferencePaymentGatewayTransactionLog *PaymentGatewayTransactionLogs `json:"ReferencePaymentGatewayTransactionLog,omitempty"` 
}
