/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// ReconciliationReports struct for ReconciliationReports
type ReconciliationReports struct {
	Id int64 `json:"Id"` 
	From *SplititTime `json:"From"` 
	To *SplititTime `json:"To"` 
	TerminalId int64 `json:"TerminalId"` 
	IsIdentical bool `json:"IsIdentical"` 
	IsDaily bool `json:"IsDaily"` 
	Terminal *Terminals `json:"Terminal,omitempty"` 
	ReconciliationReportItems []ReconciliationReportItems `json:"ReconciliationReportItems,omitempty"` 
}
