/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanActivityStatus 
type InstallmentPlanActivityStatus string

// List of InstallmentPlanActivityStatus
const (
	INSTALLMENTPLANACTIVITYSTATUS_NONE InstallmentPlanActivityStatus = "None"
	INSTALLMENTPLANACTIVITYSTATUS_ALL InstallmentPlanActivityStatus = "All"
	INSTALLMENTPLANACTIVITYSTATUS_PROCESSED InstallmentPlanActivityStatus = "Processed"
	INSTALLMENTPLANACTIVITYSTATUS_PLANNED InstallmentPlanActivityStatus = "Planned"
)
