/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// StateLimitRuleDatas struct for StateLimitRuleDatas
type StateLimitRuleDatas struct {
	Id int64 `json:"Id"` 
	TerminalId int64 `json:"TerminalId"` 
	CountrySubdivisionId int64 `json:"CountrySubdivisionId"` 
	CountrySubdivision *CountrySubdivisions `json:"CountrySubdivision,omitempty"` 
	Terminal *Terminals `json:"Terminal,omitempty"` 
}
