/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// UserStatus 
type UserStatus string

// List of UserStatus
const (
	USERSTATUS_NONE UserStatus = "None"
	USERSTATUS_ACTIVE UserStatus = "Active"
	USERSTATUS_DISABLED UserStatus = "Disabled"
)
