/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// MerchantsAllOf struct for MerchantsAllOf
type MerchantsAllOf struct {
	Name string `json:"Name,omitempty"` 
	Address string `json:"Address,omitempty"` 
	Email string `json:"Email,omitempty"` 
	MerchantAdminWebsite bool `json:"MerchantAdminWebsite"` 
	WebApi bool `json:"WebApi"` 
	EmbeddedClients bool `json:"EmbeddedClients"` 
	CrmId string `json:"CrmId,omitempty"` 
	SFParentAccountExternalId string `json:"SFParentAccountExternalId,omitempty"` 
	SFLeadId string `json:"SFLeadId,omitempty"` 
	SFParentAccountName string `json:"SFParentAccountName,omitempty"` 
	MerchantVertical string `json:"MerchantVertical,omitempty"` 
	SFAccountId string `json:"SFAccountId,omitempty"` 
	DeclaredAnnualVolumeUSD float64 `json:"DeclaredAnnualVolumeUSD,omitempty"` 
	DeclaredAOVUSD float64 `json:"DeclaredAOVUSD,omitempty"` 
	LogoImage string `json:"LogoImage,omitempty"` 
	LogoFileExtension string `json:"LogoFileExtension,omitempty"` 
	Code string `json:"Code,omitempty"` 
	SupportEmail string `json:"SupportEmail,omitempty"` 
	SupportPhone string `json:"SupportPhone,omitempty"` 
	ParameterGroupId int64 `json:"ParameterGroupId,omitempty"` 
	BusinessUnitId int64 `json:"BusinessUnitId"` 
	LogoUrl string `json:"LogoUrl,omitempty"` 
	MerchantLegalName string `json:"MerchantLegalName,omitempty"` 
	SplititMerchantId string `json:"SplititMerchantId,omitempty"` 
	WebsiteUrl string `json:"WebsiteUrl,omitempty"` 
	BillingAddressAddressLine string `json:"BillingAddressAddressLine,omitempty"` 
	BillingAddressAddressLine2 string `json:"BillingAddressAddressLine2,omitempty"` 
	BillingAddressCity string `json:"BillingAddressCity,omitempty"` 
	OrgGroup string `json:"OrgGroup,omitempty"` 
	BillingAddressCountryId int64 `json:"BillingAddressCountryId,omitempty"` 
	BillingAddressStateId int64 `json:"BillingAddressStateId,omitempty"` 
	BillingAddressZip string `json:"BillingAddressZip,omitempty"` 
	BillingAddressLegacyFullAddressLine string `json:"BillingAddressLegacyFullAddressLine,omitempty"` 
	VatTaxId string `json:"VatTaxId,omitempty"` 
	SalesAccossiateId int64 `json:"SalesAccossiateId,omitempty"` 
	RegisteredCountryOfBusinessCountryId int64 `json:"RegisteredCountryOfBusinessCountryId,omitempty"` 
	RegisteredCountryOfBusinessStateId int64 `json:"RegisteredCountryOfBusinessStateId,omitempty"` 
	MerchantCountryCountryId int64 `json:"MerchantCountryCountryId,omitempty"` 
	MerchantCountryStateId int64 `json:"MerchantCountryStateId,omitempty"` 
	BankDetailsBankAccountName string `json:"BankDetailsBankAccountName,omitempty"` 
	BankDetailsBankRoutingNumber string `json:"BankDetailsBankRoutingNumber,omitempty"` 
	BankDetailsBankAccountNumber string `json:"BankDetailsBankAccountNumber,omitempty"` 
	ReportsFolderName string `json:"ReportsFolderName,omitempty"` 
	OnBoardingMethod OnBoardingMethod `json:"OnBoardingMethod"` 
	BusinessUnit *BusinessUnits `json:"BusinessUnit,omitempty"` 
	ParameterGroup *ParameterGroups `json:"ParameterGroup,omitempty"` 
	SalesAccossiate *SalesAssociates `json:"SalesAccossiate,omitempty"` 
	ApiUsers *ApiUsers `json:"ApiUsers,omitempty"` 
	Agents []Agents `json:"Agents,omitempty"` 
	InstallmentPlanEventsSubscriptionDatas []InstallmentPlanEventsSubscriptionDatas `json:"InstallmentPlanEventsSubscriptionDatas,omitempty"` 
	Terminals []Terminals `json:"Terminals,omitempty"` 
	TouchPointColorValues []TouchPointColorValues `json:"TouchPointColorValues,omitempty"` 
	IsTest bool `json:"IsTest"` 
	MarkedForDeletion bool `json:"MarkedForDeletion"` 
	RegisteredCountryOfBusiness *CountryState `json:"RegisteredCountryOfBusiness,omitempty"` 
	MerchantCountry *CountryState `json:"MerchantCountry,omitempty"` 
	Status MerchantStatus `json:"Status"` 
	Vertical *MerchantVertical `json:"Vertical"` 
	BankDetails *BankDetails `json:"BankDetails,omitempty"` 
	BillingAddress *AddressData2 `json:"BillingAddress,omitempty"` 
	Country *Countries `json:"Country,omitempty"` 
	State *CountrySubdivisions `json:"State,omitempty"` 
	SplititSigningEntity SplititEntity `json:"SplititSigningEntity"` 
	SplititCurrentEntity SplititEntity `json:"SplititCurrentEntity"` 
}
