/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TouchPoints struct for TouchPoints
type TouchPoints struct {
	Id int64 `json:"Id"` 
	Name string `json:"Name,omitempty"` 
	Code string `json:"Code,omitempty"` 
	DefaultColorValuesId int64 `json:"DefaultColorValuesId"` 
	LogoSupported bool `json:"LogoSupported"` 
	Owner string `json:"Owner,omitempty"` 
	Url string `json:"Url,omitempty"` 
	BusinessParty BusinessParty `json:"BusinessParty,omitempty"` 
	ConfigKeys []ConfigKeys `json:"ConfigKeys,omitempty"` 
	VersionedTouchPoints []VersionedTouchPoints `json:"VersionedTouchPoints,omitempty"` 
}
