/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CartItems struct for CartItems
type CartItems struct {
	Id int64 `json:"Id"` 
	Name string `json:"Name,omitempty"` 
	Sku string `json:"Sku,omitempty"` 
	PriceAmount float64 `json:"PriceAmount"` 
	Quantity float64 `json:"Quantity"` 
	Description string `json:"Description,omitempty"` 
	InstallmentPlanId int64 `json:"InstallmentPlanId,omitempty"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
	Price *Money2 `json:"Price,omitempty"` 
}
