/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PaymentToken struct for PaymentToken
type PaymentToken struct {
	Token string `json:"Token,omitempty"` 
	Type string `json:"Type,omitempty"` 
}
