/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RequestHeader struct for RequestHeader
type RequestHeader struct {
	TouchPoint *TouchPoint `json:"TouchPoint,omitempty"` 
	SessionId string `json:"SessionId,omitempty"` 
	ApiKey string `json:"ApiKey,omitempty"` 
	CultureName string `json:"CultureName,omitempty"` 
	AuthenticationType AuthenticationType `json:"AuthenticationType,omitempty"` 
}
