/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FeeRates struct for FeeRates
type FeeRates struct {
	Id int64 `json:"Id"` 
	From int32 `json:"From"` 
	To int32 `json:"To"` 
	MerchantValue float64 `json:"MerchantValue"` 
	AgentValue float64 `json:"AgentValue"` 
	FeeRateCollectionId int64 `json:"FeeRateCollectionId"` 
	AgentFeeType AgentFeeType `json:"AgentFeeType"` 
}
