/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanStatusLogEntriesAllOf struct for InstallmentPlanStatusLogEntriesAllOf
type InstallmentPlanStatusLogEntriesAllOf struct {
	PlanId int64 `json:"PlanId"` 
	Plan *InstallmentPlans `json:"Plan,omitempty"` 
	Status InstallmentPlanStatus `json:"Status"` 
}
