/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TermsAndConditions struct for TermsAndConditions
type TermsAndConditions struct {
	Agreement string `json:"Agreement,omitempty"`
	ImportantNote string `json:"ImportantNote,omitempty"`
	FullContent string `json:"FullContent,omitempty"`
	PrivacyPolicy string `json:"PrivacyPolicy,omitempty"`
	WhatYouNeedToKnowAuthHoldDefine string `json:"WhatYouNeedToKnow_AuthHoldDefine,omitempty"`
	WhatYouNeedToKnowBudgetManagement string `json:"WhatYouNeedToKnow_BudgetManagement,omitempty"`
	WhatYouNeedToKnowCardTypeDetails string `json:"WhatYouNeedToKnow_CardTypeDetails,omitempty"`
}
