/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CountrySubdivisions struct for CountrySubdivisions
type CountrySubdivisions struct {
	Id int64 `json:"Id"` 
	CountryId int64 `json:"CountryId"` 
	IsoCode string `json:"IsoCode,omitempty"` 
	Description string `json:"Description,omitempty"` 
	Iso2Code string `json:"Iso2Code,omitempty"` 
	UtcTimeOffsetInMins int32 `json:"UtcTimeOffsetInMins"` 
	Country *Countries `json:"Country,omitempty"` 
	StateLimitRuleDatas []StateLimitRuleDatas `json:"StateLimitRuleDatas,omitempty"` 
	ZipAddressDetails []ZipAddressDetails `json:"ZipAddressDetails,omitempty"` 
}
