/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetInstallmentSchedulesRequest struct for GetInstallmentSchedulesRequest
type GetInstallmentSchedulesRequest struct {
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"` 
	Amount *MoneyWithCurrencyCode `json:"Amount,omitempty"` 
	CardNumber string `json:"CardNumber,omitempty"` 
}
