/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ProcessorType 
type ProcessorType string

// List of ProcessorType
const (
	PROCESSORTYPE_NONE ProcessorType = "None"
	PROCESSORTYPE_PAY_VISION ProcessorType = "PayVision"
	PROCESSORTYPE_NAB ProcessorType = "NAB"
	PROCESSORTYPE_AUTH_NET ProcessorType = "AuthNet"
	PROCESSORTYPE_JETPAY ProcessorType = "Jetpay"
	PROCESSORTYPE_FIRST_DATA ProcessorType = "FirstData"
	PROCESSORTYPE_CARD_CONNECT ProcessorType = "CardConnect"
	PROCESSORTYPE_PAYMENT_MANAGER ProcessorType = "PaymentManager"
)
