/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetInstallmentsScheduleResponse struct for GetInstallmentsScheduleResponse
type GetInstallmentsScheduleResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	Schedules []Schedule `json:"Schedules,omitempty"` 
	InstallmentsPicker string `json:"InstallmentsPicker,omitempty"` 
	Headline string `json:"Headline,omitempty"` 
}
