/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanCancelationReason 
type InstallmentPlanCancelationReason string

// List of InstallmentPlanCancelationReason
const (
	INSTALLMENTPLANCANCELATIONREASON_OTHER InstallmentPlanCancelationReason = "Other"
	INSTALLMENTPLANCANCELATIONREASON_CHARGE_BACK_REQUEST InstallmentPlanCancelationReason = "ChargeBackRequest"
)
