/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TransferDocumentDetailsAllOf struct for TransferDocumentDetailsAllOf
type TransferDocumentDetailsAllOf struct {
	Amount float64 `json:"Amount"` 
	TransferReason int32 `json:"TransferReason"` 
	TransferDocumentId int64 `json:"TransferDocumentId"` 
	InstallmentId int64 `json:"InstallmentId,omitempty"` 
	PlanId int64 `json:"PlanId,omitempty"` 
	Installment *Installments `json:"Installment,omitempty"` 
	Plan *InstallmentPlans `json:"Plan,omitempty"` 
	TransferDocument *TransferDocuments `json:"TransferDocument,omitempty"` 
}
