/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// ExternalAuth struct for ExternalAuth
type ExternalAuth struct {
	UniqueGatewayAuthID string `json:"UniqueGatewayAuthID,omitempty"`
	Date *SplititTime `json:"Date"`
	Amount *MoneyWithCurrencyCode `json:"Amount,omitempty"`
	TransactionFullLog string `json:"TransactionFullLog,omitempty"`
}
