/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentStatus 
type InstallmentStatus string

// List of InstallmentStatus
const (
	INSTALLMENTSTATUS_NONE InstallmentStatus = "None"
	INSTALLMENTSTATUS_WAITING_FOR_PROCESS_DATE InstallmentStatus = "WaitingForProcessDate"
	INSTALLMENTSTATUS_FINISHED InstallmentStatus = "Finished"
	INSTALLMENTSTATUS_DELETED InstallmentStatus = "Deleted"
	INSTALLMENTSTATUS_STOPPED InstallmentStatus = "Stopped"
	INSTALLMENTSTATUS_CANCELED InstallmentStatus = "Canceled"
	INSTALLMENTSTATUS_AWAITING_CAPTURE InstallmentStatus = "AwaitingCapture"
	INSTALLMENTSTATUS_AWAITING_VOID InstallmentStatus = "AwaitingVoid"
)
