/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// InstallmentPlans struct for InstallmentPlans
type InstallmentPlans struct {
	Id int64 `json:"Id"` 
	TerminalId int64 `json:"TerminalId"` 
	NumberOfInstallments int64 `json:"NumberOfInstallments"` 
	Amount float64 `json:"Amount"` 
	AmountBeforeFees float64 `json:"AmountBeforeFees"` 
	Eula bool `json:"Eula"` 
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"` 
	IsFullCaptured bool `json:"IsFullCaptured"` 
	BeginLockTime *SplititTime `json:"BeginLockTime,omitempty"` 
	MerchantFinancedDate *SplititTime `json:"MerchantFinancedDate,omitempty"` 
	MerchantReserveReturnedDate *SplititTime `json:"MerchantReserveReturnedDate,omitempty"` 
	PlannedFullCapture *SplititTime `json:"PlannedFullCapture,omitempty"` 
	InstallmentPlanTerminalDataId int64 `json:"InstallmentPlanTerminalDataId"` 
	CurrencyId int64 `json:"CurrencyId"` 
	RefOrderNumber string `json:"RefOrderNumber,omitempty"` 
	ActiveCardId int64 `json:"ActiveCardId,omitempty"` 
	Base64PngSignature string `json:"Base64PngSignature,omitempty"` 
	IsChargedBack bool `json:"IsChargedBack"` 
	AreChargesHeld bool `json:"AreChargesHeld"` 
	AutoRetry bool `json:"AutoRetry"` 
	PisMemberUniqueId string `json:"PisMemberUniqueId,omitempty"` 
	PisMemberId int64 `json:"PisMemberId,omitempty"` 
	Subtotal float64 `json:"Subtotal"` 
	Tax float64 `json:"Tax"` 
	Shipping float64 `json:"Shipping"` 
	SetupContextId int64 `json:"SetupContextId"` 
	OriginalAmount float64 `json:"OriginalAmount"` 
	RefundAmount float64 `json:"RefundAmount"` 
	ReservePoolAmount float64 `json:"ReservePoolAmount"` 
	ShopperApprovalDateTime *SplititTime `json:"ShopperApprovalDateTime,omitempty"` 
	CancellationDateTime *SplititTime `json:"CancellationDateTime,omitempty"` 
	ActivatedDate *SplititTime `json:"ActivatedDate,omitempty"` 
	DeActivatedDate *SplititTime `json:"DeActivatedDate,omitempty"` 
	AmountForFunding float64 `json:"AmountForFunding"` 
	AmountForFundingCurrency *Currencies `json:"AmountForFunding_Currency,omitempty"` 
	AmountForFundingExchangeRate float64 `json:"AmountForFunding_ExchangeRate"` 
	AmountForFundingTransactionCurrency float64 `json:"AmountForFunding_TransactionCurrency"` 
	ActiveCard *Cards `json:"ActiveCard,omitempty"` 
	Currency *Currencies `json:"Currency,omitempty"` 
	InstallmentPlanTerminalData *InstallmentPlanTerminalDatas `json:"InstallmentPlanTerminalData,omitempty"` 
	PisMember *PisMembers `json:"PisMember,omitempty"` 
	SetupContext *InstallmentPlanSetupContexts `json:"SetupContext,omitempty"` 
	Terminal *Terminals `json:"Terminal,omitempty"` 
	CartItems []CartItems `json:"CartItems,omitempty"` 
	EmailAuditLogs []EmailAuditLogs `json:"EmailAuditLogs,omitempty"` 
	FeesDocuments []FeesDocuments `json:"FeesDocuments,omitempty"` 
	FraudDetectionLogs []FraudDetectionLogs `json:"FraudDetectionLogs,omitempty"` 
	FundingCollectDocumentDetails []FundingCollectDocumentDetails `json:"FundingCollectDocumentDetails,omitempty"` 
	InstallmentPlanAuditLogs []InstallmentPlanAuditLogs `json:"InstallmentPlanAuditLogs,omitempty"` 
	InstallmentPlanEvents []InstallmentPlanEvents `json:"InstallmentPlanEvents,omitempty"` 
	InstallmentPlanStatusLogEntries []InstallmentPlanStatusLogEntries `json:"InstallmentPlanStatusLogEntries,omitempty"` 
	Installments []Installments `json:"Installments,omitempty"` 
	ReAuthorizations []ReAuthorizations `json:"ReAuthorizations,omitempty"` 
	RefundLogEntries []RefundLogEntries `json:"RefundLogEntries,omitempty"` 
	TransferDocumentDetails []TransferDocumentDetails `json:"TransferDocumentDetails,omitempty"` 
	ActiveTerminalDataId int64 `json:"ActiveTerminalDataId,omitempty"` 
	ActiveTerminalData *TerminalGatewayDatas `json:"ActiveTerminalData,omitempty"` 
	DelayResolution DelayResolution `json:"DelayResolution,omitempty"` 
	TestMode TestModes `json:"TestMode"` 
	FundingTypesId MoneyFlows `json:"FundingTypesId"` 
	Strategy PlanStrategy `json:"Strategy"` 
	Status InstallmentPlanStatus `json:"Status"` 
	PurchaseMethod PurchaseMethod `json:"PurchaseMethod"` 
	ExtendedParamsSerializedData string `json:"ExtendedParamsSerializedData,omitempty"` 
	ExtendedParams map[string]string `json:"ExtendedParams,omitempty"` 
	AutoCapture bool `json:"AutoCapture"` 
	Items []CartItems `json:"Items,omitempty"` 
	AmountDetails *AmountDetails2 `json:"AmountDetails,omitempty"` 
}
