/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ProcessorAuthenticationParameters struct for ProcessorAuthenticationParameters
type ProcessorAuthenticationParameters struct {
	Id int64 `json:"Id"` 
	DisplayName string `json:"DisplayName,omitempty"` 
	Key string `json:"Key,omitempty"` 
	Order int32 `json:"Order"` 
	ProcessorId int64 `json:"ProcessorId,omitempty"` 
	Processor *Processors `json:"Processor,omitempty"` 
}
