/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetInitiatedUpdatePaymentDataResponse struct for GetInitiatedUpdatePaymentDataResponse
type GetInitiatedUpdatePaymentDataResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	CardData *CardData `json:"CardData,omitempty"` 
	Merchant *MerchantRef `json:"Merchant,omitempty"` 
	RedirectUrls *RedirectUrls `json:"RedirectUrls,omitempty"` 
	OutstandingAmount *MoneyWithCurrencyCode `json:"OutstandingAmount,omitempty"` 
	TermsAndConditions *TermsAndConditions `json:"TermsAndConditions,omitempty"` 
	ProcessorName string `json:"ProcessorName,omitempty"` 
	Is3DSRequired bool `json:"Is3DSRequired"` 
	LastError *Error `json:"LastError,omitempty"` 
	Logo string `json:"Logo,omitempty"` 
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"` 
}
