/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TestCardRequest struct for TestCardRequest
type TestCardRequest struct {
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"` 
	DoVoid bool `json:"DoVoid,omitempty"` 
}
