/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanStatus 
type InstallmentPlanStatus string

// List of InstallmentPlanStatus
const (
	INSTALLMENTPLANSTATUS_NONE InstallmentPlanStatus = "None"
	INSTALLMENTPLANSTATUS_PENDING_APPROVAL InstallmentPlanStatus = "PendingApproval"
	INSTALLMENTPLANSTATUS_PENDING_MERCHANT_SHIPMENT_NOTICE InstallmentPlanStatus = "PendingMerchantShipmentNotice"
	INSTALLMENTPLANSTATUS_IN_PROGRESS InstallmentPlanStatus = "InProgress"
	INSTALLMENTPLANSTATUS_DELETED InstallmentPlanStatus = "Deleted"
	INSTALLMENTPLANSTATUS_CLEARED InstallmentPlanStatus = "Cleared"
	INSTALLMENTPLANSTATUS_PENDING_PAYMENT_UPDATE InstallmentPlanStatus = "PendingPaymentUpdate"
	INSTALLMENTPLANSTATUS_CANCELED InstallmentPlanStatus = "Canceled"
	INSTALLMENTPLANSTATUS_DELAYED InstallmentPlanStatus = "Delayed"
	INSTALLMENTPLANSTATUS_INITIALIZING InstallmentPlanStatus = "Initializing"
	INSTALLMENTPLANSTATUS_ALL_STATUSES InstallmentPlanStatus = "AllStatuses"
)
