/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PagingResponseHeader struct for PagingResponseHeader
type PagingResponseHeader struct {
	TotalNumber int64 `json:"TotalNumber"`
}
