/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FraudDetectionLogsAllOf struct for FraudDetectionLogsAllOf
type FraudDetectionLogsAllOf struct {
	InstallmentPlanId int64 `json:"InstallmentPlanId"` 
	FullLog string `json:"FullLog,omitempty"` 
	ProviderResultDescription string `json:"ProviderResultDescription,omitempty"` 
	ProviderResultCode string `json:"ProviderResultCode,omitempty"` 
	ProviderReferenceId string `json:"ProviderReferenceId,omitempty"` 
	TimeLapse int64 `json:"TimeLapse"` 
	CardId int64 `json:"CardId"` 
	Provider string `json:"Provider,omitempty"` 
	PaymentGateWayTransactionLogId int64 `json:"PaymentGateWayTransactionLogId,omitempty"` 
	Card *Cards `json:"Card,omitempty"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
	PaymentGateWayTransactionLog *PaymentGatewayTransactionLogs `json:"PaymentGateWayTransactionLog,omitempty"` 
	Result FraudCheckResult `json:"Result"` 
}
