/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ChbDefaultAction 
type ChbDefaultAction string

// List of ChbDefaultAction
const (
	CHBDEFAULTACTION_NONE ChbDefaultAction = "None"
	CHBDEFAULTACTION_CANCEL_INSTALLMENTS_PLAN ChbDefaultAction = "CancelInstallmentsPlan"
	CHBDEFAULTACTION_PERFORM_FULL_CAPTURE ChbDefaultAction = "PerformFullCapture"
	CHBDEFAULTACTION_FREEZE_INSTALLMENTS_PLAN ChbDefaultAction = "FreezeInstallmentsPlan"
	CHBDEFAULTACTION_CHOOSE ChbDefaultAction = "Choose"
)
