/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// ReAuthorization struct for ReAuthorization
type ReAuthorization struct {
	ProcessingDate *SplititTime `json:"ProcessingDate,omitempty"`
	Amount *Money `json:"Amount,omitempty"`
	TransactionResults *[]TransactionResult `json:"TransactionResults,omitempty"`
	CardDetails *CardData `json:"CardDetails,omitempty"`
	Result bool `json:"Result,omitempty"`
}
