/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// InstallmentPlanEventSubscriberRecordSendLogs struct for InstallmentPlanEventSubscriberRecordSendLogs
type InstallmentPlanEventSubscriberRecordSendLogs struct {
	Id int64 `json:"Id"` 
	InstallmentPlanEventSubscriberRecordId int64 `json:"InstallmentPlanEventSubscriberRecordId"` 
	SendTime *SplititTime `json:"SendTime"` 
	Response string `json:"Response,omitempty"` 
	InstallmentPlanEventSubscriberRecord *InstallmentPlanEventSubscriberRecords `json:"InstallmentPlanEventSubscriberRecord,omitempty"` 
}
