/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// ExtendedInstallmentPlan struct for ExtendedInstallmentPlan
type ExtendedInstallmentPlan struct {
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"`
	InstallmentPlanStatus *ReferenceEntityBase `json:"InstallmentPlanStatus,omitempty"`
	Amount *Money `json:"Amount,omitempty"`
	OutstandingAmount *Money `json:"OutstandingAmount,omitempty"`
	NumberOfInstallments int32 `json:"NumberOfInstallments"`
	NumberOfProcessedInstallments int32 `json:"NumberOfProcessedInstallments"`
	OriginalAmount *Money `json:"OriginalAmount,omitempty"`
	RefundAmount *Money `json:"RefundAmount,omitempty"`
	Consumer *ConsumerData `json:"Consumer,omitempty"`
	ActiveCard *CardData `json:"ActiveCard,omitempty"`
	FraudCheck *FraudCheck `json:"FraudCheck,omitempty"`
	Merchant *MerchantRef `json:"Merchant,omitempty"`
	RefOrderNumber string `json:"RefOrderNumber,omitempty"`
	PurchaseMethod *ReferenceEntityBase `json:"PurchaseMethod,omitempty"`
	Strategy *ReferenceEntityBase `json:"Strategy,omitempty"`
	DelayResolution *ReferenceEntityBase `json:"DelayResolution,omitempty"`
	ExtendedParams map[string]string `json:"ExtendedParams,omitempty"`
	IsFullCaptured bool `json:"IsFullCaptured"`
	IsChargedBack bool `json:"IsChargedBack"`
	ArePaymentsOnHold bool `json:"ArePaymentsOnHold"`
	ScpFundingPercent float64 `json:"ScpFundingPercent"`
	TestMode *TestModes `json:"TestMode"`
	CreationDateTime *SplititTime `json:"CreationDateTime"`
	Installments *[]Installment2 `json:"Installments,omitempty"`
	SecureAuthorizations *[]ReAuthorization `json:"SecureAuthorizations,omitempty"`
	BusinessUnit *BuRef `json:"BusinessUnit,omitempty"`
	ShopperPaymentRequestTime *SplititTime `json:"ShopperPaymentRequestTime,omitempty"`
}
