/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// DisputeStatus 
type DisputeStatus string

// List of DisputeStatus
const (
	DISPUTESTATUS_OPEN DisputeStatus = "Open"
	DISPUTESTATUS_WON DisputeStatus = "Won"
	DISPUTESTATUS_LOST DisputeStatus = "Lost"
	DISPUTESTATUS_CLOSED DisputeStatus = "Closed"
	DISPUTESTATUS_OTHER DisputeStatus = "Other"
)
