/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// Agents struct for Agents
type Agents struct {
	Id int64 `json:"Id"` 
	AgentNumber string `json:"AgentNumber,omitempty"` 
	Email string `json:"Email,omitempty"` 
	FirstName string `json:"FirstName,omitempty"` 
	LastName string `json:"LastName,omitempty"` 
	JobTitle string `json:"JobTitle,omitempty"` 
	FaxNumber string `json:"FaxNumber,omitempty"` 
	MobileNumber string `json:"MobileNumber,omitempty"` 
	WorkPhoneNumber string `json:"WorkPhoneNumber,omitempty"` 
	Notes string `json:"Notes,omitempty"` 
	CrmId string `json:"CrmId,omitempty"` 
	PisUserUniqueId string `json:"PisUserUniqueId,omitempty"` 
	MerchantId int64 `json:"MerchantId,omitempty"` 
	PisUserId int64 `json:"PisUserId,omitempty"` 
	Merchant *Merchants `json:"Merchant,omitempty"` 
	PisUser *PisUsers `json:"PisUser,omitempty"` 
	Terminals []Terminals `json:"Terminals,omitempty"` 
}
