/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// BinDataItems struct for BinDataItems
type BinDataItems struct {
	Id int64 `json:"Id"` 
	LowBin string `json:"LowBin,omitempty"` 
	HighBin string `json:"HighBin,omitempty"` 
	BinLength int32 `json:"BinLength"` 
	BinDetailPan int32 `json:"BinDetailPan"` 
	IssuerBankName string `json:"IssuerBankName,omitempty"` 
	IssueCountryId int64 `json:"IssueCountryId,omitempty"` 
	DetailCardIndicator string `json:"DetailCardIndicator,omitempty"` 
	IssuerUpdateDate *SplititTime `json:"IssuerUpdateDate"` 
	EbtState string `json:"EbtState,omitempty"` 
	IsDebitSignatureNetworkParticipant bool `json:"IsDebitSignatureNetworkParticipant"` 
	IsFsa bool `json:"IsFsa"` 
	IsPrepaid bool `json:"IsPrepaid"` 
	ProductId string `json:"ProductId,omitempty"` 
	RegulatorIndicator string `json:"RegulatorIndicator,omitempty"` 
	VisaProductSubType string `json:"VisaProductSubType,omitempty"` 
	VisaLargeTicketIndicator string `json:"VisaLargeTicketIndicator,omitempty"` 
	AccountLevelProcessingIndicator string `json:"AccountLevelProcessingIndicator,omitempty"` 
	CardClass string `json:"CardClass,omitempty"` 
	PanLengthMin int32 `json:"PanLengthMin"` 
	PanLengthMax int32 `json:"PanLengthMax"` 
	TokenIndicator string `json:"TokenIndicator,omitempty"` 
	IssuingNetwork string `json:"IssuingNetwork,omitempty"` 
	CardHolderBillingCurrency string `json:"CardHolderBillingCurrency,omitempty"` 
	MoneySendIndicator string `json:"MoneySendIndicator,omitempty"` 
	OriginalCreditMoneyTransferIndicator string `json:"OriginalCreditMoneyTransferIndicator,omitempty"` 
	OriginalCreditOnlineGamblingIndicator string `json:"OriginalCreditOnlineGamblingIndicator,omitempty"` 
	OriginalCreditTransactionIndicator string `json:"OriginalCreditTransactionIndicator,omitempty"` 
	FastFunds string `json:"FastFunds,omitempty"` 
	ReservedField string `json:"ReservedField,omitempty"` 
	IssueCountry *Countries `json:"IssueCountry,omitempty"` 
	CardBrand CardBrand `json:"CardBrand"` 
	CardType CardType `json:"CardType"` 
}
