/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CardsAllOf struct for CardsAllOf
type CardsAllOf struct {
	KekId int64 `json:"KekId"` 
	BinBinNumber string `json:"BinBinNumber,omitempty"` 
	BinIssuingCountryIsoNumber string `json:"BinIssuingCountryIsoNumber,omitempty"` 
	BinId int64 `json:"BinId"` 
	ExpirationMonth int32 `json:"ExpirationMonth"` 
	ExpirationYear int32 `json:"ExpirationYear"` 
	AddressDataAddressLine string `json:"AddressDataAddressLine,omitempty"` 
	AddressDataZip string `json:"AddressDataZip,omitempty"` 
	IsDeleted bool `json:"IsDeleted"` 
	Version int32 `json:"Version"` 
	PisMemberUniqueId string `json:"PisMemberUniqueId,omitempty"` 
	PisMemberId int64 `json:"PisMemberId,omitempty"` 
	AddressDataAddressLine2 string `json:"AddressDataAddressLine2,omitempty"` 
	AddressDataCity string `json:"AddressDataCity,omitempty"` 
	AddressDataCountryId int64 `json:"AddressDataCountryId,omitempty"` 
	AddressDataStateId int64 `json:"AddressDataStateId,omitempty"` 
	AddressDataLegacyFullAddressLine string `json:"AddressDataLegacyFullAddressLine,omitempty"` 
	BinIsPrepaid bool `json:"BinIsPrepaid,omitempty"` 
	Token string `json:"Token,omitempty"` 
	Kek *Keks `json:"Kek,omitempty"` 
	CardClass string `json:"CardClass,omitempty"` 
	ProductId string `json:"ProductId,omitempty"` 
	IssuerBankName string `json:"IssuerBankName,omitempty"` 
	DekDataId int64 `json:"DekDataId,omitempty"` 
	DekData *DekData `json:"DekData,omitempty"` 
	PisMember *PisMembers `json:"PisMember,omitempty"` 
	AccountUpdaterPendingCards []AccountUpdaterPendingCards `json:"AccountUpdaterPendingCards,omitempty"` 
	CardStateLogs []CardStateLogs `json:"CardStateLogs,omitempty"` 
	FraudDetectionLogs []FraudDetectionLogs `json:"FraudDetectionLogs,omitempty"` 
	InstallmentPlanAuditLogs []InstallmentPlanAuditLogs `json:"InstallmentPlanAuditLogs,omitempty"` 
	InstallmentPlans []InstallmentPlans `json:"InstallmentPlans,omitempty"` 
	AddressData *AddressData2 `json:"AddressData,omitempty"` 
	EncryptedNumber string `json:"EncryptedNumber,omitempty"` 
	Dek string `json:"Dek,omitempty"` 
	MaskedNumber string `json:"MaskedNumber,omitempty"` 
	CardHolderName string `json:"CardHolderName,omitempty"` 
	BinCardBrand CardBrand `json:"BinCardBrand"` 
	BinCardType CardType `json:"BinCardType"` 
	Cvv string `json:"Cvv,omitempty"` 
	Bin *BinData `json:"Bin,omitempty"` 
	Country *Countries `json:"Country,omitempty"` 
	State *CountrySubdivisions `json:"State,omitempty"` 
}
