/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FundingCollectDocumentDetails struct for FundingCollectDocumentDetails
type FundingCollectDocumentDetails struct {
	Id int64 `json:"Id"` 
	Amount float64 `json:"Amount"` 
	CollectDocumentId int64 `json:"CollectDocumentId"` 
	InstallmentId int64 `json:"InstallmentId,omitempty"` 
	PlanId int64 `json:"PlanId,omitempty"` 
	CollectDocument *CollectDocuments `json:"CollectDocument,omitempty"` 
	Installment *Installments `json:"Installment,omitempty"` 
	Plan *InstallmentPlans `json:"Plan,omitempty"` 
	FundingPayDocumentDetails []FundingPayDocumentDetails `json:"FundingPayDocumentDetails,omitempty"` 
	TransferReason FundingTransferReason `json:"TransferReason"` 
}
