/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// SessionAvailibility 
type SessionAvailibility string

// List of SessionAvailibility
const (
	SESSIONAVAILIBILITY_PRIVATE SessionAvailibility = "Private"
	SESSIONAVAILIBILITY_PUBLIC SessionAvailibility = "Public"
)
