/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RedirectUrls struct for RedirectUrls
type RedirectUrls struct {
	Succeeded string `json:"Succeeded,omitempty"` 
	Canceled string `json:"Canceled,omitempty"` 
	Failed string `json:"Failed,omitempty"` 
}
