/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// MoneyWithCurrencyCode struct for MoneyWithCurrencyCode
type MoneyWithCurrencyCode struct {
	Value float64 `json:"Value"` 
	CurrencyCode string `json:"CurrencyCode,omitempty"` 
}
