/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// AccountUpdaterSubscribersScopesAllOf struct for AccountUpdaterSubscribersScopesAllOf
type AccountUpdaterSubscribersScopesAllOf struct {
	TerminalId int64 `json:"TerminalId"` 
	IssuingCountryIso string `json:"IssuingCountryIso,omitempty"` 
	Terminal *Terminals `json:"Terminal,omitempty"` 
	AccountUpdaterProvider AccountUpdaterProvider `json:"AccountUpdaterProvider"` 
	CardBrand CardBrand `json:"CardBrand"` 
}
