/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RefundInstallmentPlanResponseAllOf struct for RefundInstallmentPlanResponseAllOf
type RefundInstallmentPlanResponseAllOf struct {
	CurrentRefundAmount *Money `json:"CurrentRefundAmount,omitempty"` 
}
