/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetResourcesRequestContext struct for GetResourcesRequestContext
type GetResourcesRequestContext struct {
	MerchantCode string `json:"MerchantCode,omitempty"`
	CultureName string `json:"CultureName,omitempty"`
	TouchPointCode string `json:"TouchPointCode,omitempty"`
}
