/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// ApplicativeUserAllOf struct for ApplicativeUserAllOf
type ApplicativeUserAllOf struct {
	LastTimeLogin *SplititTime `json:"LastTimeLogin"` 
	IsDataPrivateRestricted bool `json:"IsDataPrivateRestricted"` 
}
