/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TouchPoint struct for TouchPoint
type TouchPoint struct {
	Code string `json:"Code,omitempty"` 
	Version string `json:"Version,omitempty"` 
	SubVersion string `json:"SubVersion,omitempty"` 
	VersionedTouchpointId int64 `json:"VersionedTouchpointId,omitempty"` 
}
