/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ScheduleElements struct for ScheduleElements
type ScheduleElements struct {
	InstallmentNumber int32 `json:"InstallmentNumber"` 
	ChargeDate string `json:"ChargeDate,omitempty"` 
	ChargeAmount float64 `json:"ChargeAmount"` 
	RequiredCredit float64 `json:"RequiredCredit"` 
}
