/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// CollectDocumentsAllOf struct for CollectDocumentsAllOf
type CollectDocumentsAllOf struct {
	Amount float64 `json:"Amount"` 
	CurrencyId int64 `json:"CurrencyId"` 
	BusinessUnitId int64 `json:"BusinessUnitId"` 
	ApprovalDate *SplititTime `json:"ApprovalDate,omitempty"` 
	Discriminator string `json:"Discriminator,omitempty"` 
	LenderId int64 `json:"LenderId,omitempty"` 
	ExcludeFromEmails bool `json:"ExcludeFromEmails,omitempty"` 
	BusinessUnit *BusinessUnits `json:"BusinessUnit,omitempty"` 
	Currency *Currencies `json:"Currency,omitempty"` 
	Lender *ScpProviders `json:"Lender,omitempty"` 
	FundingCollectDocumentDetails []FundingCollectDocumentDetails `json:"FundingCollectDocumentDetails,omitempty"` 
}
