/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanEventType 
type InstallmentPlanEventType string

// List of InstallmentPlanEventType
const (
	INSTALLMENTPLANEVENTTYPE_SECURE_AUTH_SUCCEEDED InstallmentPlanEventType = "SecureAuthSucceeded"
	INSTALLMENTPLANEVENTTYPE_SECURE_AUTH_FAILED InstallmentPlanEventType = "SecureAuthFailed"
	INSTALLMENTPLANEVENTTYPE_CHARGE_SUCCEEDED InstallmentPlanEventType = "ChargeSucceeded"
	INSTALLMENTPLANEVENTTYPE_CHARGE_FAILED InstallmentPlanEventType = "ChargeFailed"
	INSTALLMENTPLANEVENTTYPE_REFUND_SUCCEEDED InstallmentPlanEventType = "RefundSucceeded"
	INSTALLMENTPLANEVENTTYPE_REFUND_FAILED InstallmentPlanEventType = "RefundFailed"
	INSTALLMENTPLANEVENTTYPE_FULL_CAPTURE_SUCCEEDED InstallmentPlanEventType = "FullCaptureSucceeded"
	INSTALLMENTPLANEVENTTYPE_FULL_CAPTURE_FAILED InstallmentPlanEventType = "FullCaptureFailed"
	INSTALLMENTPLANEVENTTYPE_PLAN_CREATED_SUCCEEDED InstallmentPlanEventType = "PlanCreatedSucceeded"
	INSTALLMENTPLANEVENTTYPE_PLAN_CREATED_FAILED InstallmentPlanEventType = "PlanCreatedFailed"
	INSTALLMENTPLANEVENTTYPE_PLAN_APPROVED_SUCCEEDED InstallmentPlanEventType = "PlanApprovedSucceeded"
	INSTALLMENTPLANEVENTTYPE_PLAN_APPROVED_FAILED InstallmentPlanEventType = "PlanApprovedFailed"
	INSTALLMENTPLANEVENTTYPE_PLAN_UPDATED_SUCCEEDED InstallmentPlanEventType = "PlanUpdatedSucceeded"
	INSTALLMENTPLANEVENTTYPE_PLAN_UPDATED_FAILED InstallmentPlanEventType = "PlanUpdatedFailed"
	INSTALLMENTPLANEVENTTYPE_PLAN_CANCELLED_SUCCEEDED InstallmentPlanEventType = "PlanCancelledSucceeded"
	INSTALLMENTPLANEVENTTYPE_PLAN_CANCELLED_FAILED InstallmentPlanEventType = "PlanCancelledFailed"
	INSTALLMENTPLANEVENTTYPE_CUSTOMER_CREDIT_CARD_UPDATE_SUCCEEDED InstallmentPlanEventType = "CustomerCreditCardUpdateSucceeded"
	INSTALLMENTPLANEVENTTYPE_CUSTOMER_CREDIT_CARD_UPDATE_FAILED InstallmentPlanEventType = "CustomerCreditCardUpdateFailed"
	INSTALLMENTPLANEVENTTYPE_CUSTOMER_DETAILS_UPDATE_SUCCEEDED InstallmentPlanEventType = "CustomerDetailsUpdateSucceeded"
	INSTALLMENTPLANEVENTTYPE_CUSTOMER_DETAILS_UPDATE_FAILED InstallmentPlanEventType = "CustomerDetailsUpdateFailed"
	INSTALLMENTPLANEVENTTYPE_START_INSTALLMENTS_SUCCEEDED InstallmentPlanEventType = "StartInstallmentsSucceeded"
	INSTALLMENTPLANEVENTTYPE_START_INSTALLMENTS_FAILED InstallmentPlanEventType = "StartInstallmentsFailed"
	INSTALLMENTPLANEVENTTYPE_PLAN_CLEARED InstallmentPlanEventType = "PlanCleared"
	INSTALLMENTPLANEVENTTYPE_PLAN_DELAYED InstallmentPlanEventType = "PlanDelayed"
	INSTALLMENTPLANEVENTTYPE_PLAN_RECOVERED InstallmentPlanEventType = "PlanRecovered"
	INSTALLMENTPLANEVENTTYPE_PLAN_SECURED_AUTH_REMINDER_SHOULD_BE_SENT InstallmentPlanEventType = "PlanSecuredAuthReminderShouldBeSent"
	INSTALLMENTPLANEVENTTYPE_RETRY_SUCCEEDED InstallmentPlanEventType = "RetrySucceeded"
	INSTALLMENTPLANEVENTTYPE_RETRY_FAILED InstallmentPlanEventType = "RetryFailed"
	INSTALLMENTPLANEVENTTYPE_PLAN_DELETED InstallmentPlanEventType = "PlanDeleted"
	INSTALLMENTPLANEVENTTYPE_REFUND_COMPLETED InstallmentPlanEventType = "RefundCompleted"
)
