/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanEventsSubscriptionDatas struct for InstallmentPlanEventsSubscriptionDatas
type InstallmentPlanEventsSubscriptionDatas struct {
	Id int64 `json:"Id"` 
	SubscribedEventsString string `json:"SubscribedEventsString,omitempty"` 
	MerchantId int64 `json:"MerchantId"` 
	EventSubscriptionEndPointUrl string `json:"EventSubscriptionEndPointUrl,omitempty"` 
	Merchant *Merchants `json:"Merchant,omitempty"` 
	SubscribedEvent InstallmentPlanEventType `json:"SubscribedEvent"` 
}
