/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InitiateInstallmentPlanRequest struct for InitiateInstallmentPlanRequest
type InitiateInstallmentPlanRequest struct {
	PlanData *PlanData `json:"PlanData,omitempty"` 
	CartData *CartData `json:"CartData,omitempty"` 
	ConsumerData *ConsumerData `json:"ConsumerData,omitempty"` 
	BillingAddress *AddressData `json:"BillingAddress,omitempty"` 
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"` 
	PaymentWizardData *PaymentWizardData `json:"PaymentWizardData,omitempty"` 
	RedirectUrls *RedirectUrls `json:"RedirectUrls,omitempty"` 
	EventsEndpoints *EventsEndpoints `json:"EventsEndpoints,omitempty"` 
	CreditCardDetails *CardData `json:"CreditCardDetails,omitempty"` 
}
