/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PisUserBusinessUnits struct for PisUserBusinessUnits
type PisUserBusinessUnits struct {
	PisUserUniqueId string `json:"PisUserUniqueId,omitempty"` 
	PisUserId int64 `json:"PisUserId"` 
	BusinessUnitId int64 `json:"BusinessUnitId"` 
	BusinessUnit *BusinessUnits `json:"BusinessUnit,omitempty"` 
	PisUser *PisUsers `json:"PisUser,omitempty"` 
}
