/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// LoginResponse2 struct for LoginResponse2
type LoginResponse2 struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	SessionId string `json:"SessionId,omitempty"` 
}
