/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// BankDetails struct for BankDetails
type BankDetails struct {
	BankAccountName string `json:"BankAccountName,omitempty"` 
	BankRoutingNumber string `json:"BankRoutingNumber,omitempty"` 
	BankAccountNumber string `json:"BankAccountNumber,omitempty"` 
}
