/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetPgtlResponse struct for GetPgtlResponse
type GetPgtlResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	PaymentGatewaytransactionResponses map[string][]PaymentGatewayTransactionLogs `json:"paymentGatewaytransactionResponses,omitempty"` 
}
