/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// IntegrationType 
type IntegrationType string

// List of IntegrationType
const (
	INTEGRATIONTYPE_NONE IntegrationType = "None"
	INTEGRATIONTYPE_SHOPIFY IntegrationType = "Shopify"
	INTEGRATIONTYPE_WOOCOMMERCE IntegrationType = "Woocommerce"
)
