/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// RefundUnderCancelation 
type RefundUnderCancelation string

// List of RefundUnderCancelation
const (
	REFUNDUNDERCANCELATION_NONE RefundUnderCancelation = "None"
	REFUNDUNDERCANCELATION_NO_REFUNDS RefundUnderCancelation = "NoRefunds"
	REFUNDUNDERCANCELATION_ONLY_IF_A_FULL_REFUND_IS_POSSIBLE RefundUnderCancelation = "OnlyIfAFullRefundIsPossible"
	REFUNDUNDERCANCELATION_CHOOSE RefundUnderCancelation = "Choose"
)
