/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PisUsersAllOf struct for PisUsersAllOf
type PisUsersAllOf struct {
	CrmId string `json:"CrmId,omitempty"` 
	Agents []Agents `json:"Agents,omitempty"` 
	PisUserBusinessUnits []PisUserBusinessUnits `json:"PisUserBusinessUnits,omitempty"` 
	PisUserPasswordHistories []PisUserPasswordHistories `json:"PisUserPasswordHistories,omitempty"` 
	UserJobSubscriptions []UserJobSubscriptions `json:"UserJobSubscriptions,omitempty"` 
	UserFullName string `json:"UserFullName,omitempty"` 
	Password *IUserPasswordHistory `json:"Password,omitempty"` 
}
