/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetFraudStatusDisplayResponse struct for GetFraudStatusDisplayResponse
type GetFraudStatusDisplayResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"`
	Provider string `json:"Provider,omitempty"`
	FullLog string `json:"FullLog,omitempty"`
	ProviderResultDescription string `json:"ProviderResultDescription,omitempty"`
	InstallmentPlanId int64 `json:"InstallmentPlanId"`
	ProviderResultCode string `json:"ProviderResultCode,omitempty"`
}
