/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ReAuthorizationPaymentGatewayTransactionLogs struct for ReAuthorizationPaymentGatewayTransactionLogs
type ReAuthorizationPaymentGatewayTransactionLogs struct {
	ReAuthorizationId int64 `json:"ReAuthorizationId"` 
	PaymentGatewayTransactionLogId int64 `json:"PaymentGatewayTransactionLogId"` 
	PaymentGatewayTransactionLog *PaymentGatewayTransactionLogs `json:"PaymentGatewayTransactionLog,omitempty"` 
	ReAuthorization *ReAuthorizations `json:"ReAuthorization,omitempty"` 
}
