/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PisMembersAllOf struct for PisMembersAllOf
type PisMembersAllOf struct {
	IsWelcomeMailSent bool `json:"IsWelcomeMailSent"` 
	ConsumerFullName string `json:"ConsumerFullName,omitempty"` 
	Cards []Cards `json:"Cards,omitempty"` 
	PisMemberPasswordHistories []PisMemberPasswordHistories `json:"PisMemberPasswordHistories,omitempty"` 
	UserFullName string `json:"UserFullName,omitempty"` 
	Password *IUserPasswordHistory `json:"Password,omitempty"` 
	LoginUserName string `json:"LoginUserName,omitempty"` 
}
