/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// Installment2 struct for Installment2
type Installment2 struct {
	InstallmentNumber int32 `json:"InstallmentNumber"` 
	Amount *Money `json:"Amount,omitempty"` 
	OriginalAmount *Money `json:"OriginalAmount,omitempty"` 
	RefundAmount *Money `json:"RefundAmount,omitempty"` 
	ProcessDateTime *SplititTime `json:"ProcessDateTime,omitempty"` 
	IsRefund bool `json:"IsRefund"` 
	RequiredCredit *Money `json:"RequiredCredit,omitempty"` 
	CreatedDateTime *SplititTime `json:"CreatedDateTime"` 
	Status *ReferenceEntityBase `json:"Status,omitempty"` 
	TransactionResults []TransactionResult `json:"TransactionResults,omitempty"` 
	CardDetails *CardData `json:"CardDetails,omitempty"` 
	Result bool `json:"Result,omitempty"` 
}
