/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FundingPayDocumentDetailsAllOf struct for FundingPayDocumentDetailsAllOf
type FundingPayDocumentDetailsAllOf struct {
	PayDocumentId int64 `json:"PayDocumentId,omitempty"` 
	PlanId int64 `json:"PlanId,omitempty"` 
	Amount float64 `json:"Amount"` 
	Plan *InstallmentPlans `json:"Plan,omitempty"` 
	CollectDocumentDetailsId int64 `json:"CollectDocumentDetailsId,omitempty"` 
	CollectDocumentDetails *FundingCollectDocumentDetails `json:"CollectDocumentDetails,omitempty"` 
	PayDocument *PayDocuments `json:"PayDocument,omitempty"` 
}
