/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// AccountingParty 
type AccountingParty string

// List of AccountingParty
const (
	ACCOUNTINGPARTY_SCP AccountingParty = "Scp"
	ACCOUNTINGPARTY_AGENT AccountingParty = "Agent"
	ACCOUNTINGPARTY_MERCHANT AccountingParty = "Merchant"
	ACCOUNTINGPARTY_SPLITIT_USA AccountingParty = "SplititUsa"
	ACCOUNTINGPARTY_SPLITIT_CAPITAL AccountingParty = "SplititCapital"
)
