/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PagingRequestHeader struct for PagingRequestHeader
type PagingRequestHeader struct {
	Skip int32 `json:"Skip"`
	Take int32 `json:"Take"`
}
