/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ParameterGroupsAllOf struct for ParameterGroupsAllOf
type ParameterGroupsAllOf struct {
	Tokens []Tokens `json:"Tokens,omitempty"` 
	Merchants []Merchants `json:"Merchants,omitempty"` 
	Parameters []Parameters `json:"Parameters,omitempty"` 
	SplititJobDefinitions []SplititJobDefinitions `json:"SplititJobDefinitions,omitempty"` 
}
