/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ScpProvidersAllOf struct for ScpProvidersAllOf
type ScpProvidersAllOf struct {
	Id int64 `json:"Id"` 
	Name string `json:"Name,omitempty"` 
	ImplementationCode string `json:"ImplementationCode,omitempty"` 
	TotalFunds float64 `json:"TotalFunds"` 
	MaxNonSecurePlansPercent float64 `json:"MaxNonSecurePlansPercent"` 
	ScpVariableCostAnnualPercent float64 `json:"ScpVariableCostAnnualPercent"` 
	ScpFixedCost float64 `json:"ScpFixedCost"` 
	ScpRevenueSharePercent float64 `json:"ScpRevenueSharePercent"` 
	TotalFundsCurrencyId int64 `json:"TotalFundsCurrencyId,omitempty"` 
	EmailsList string `json:"EmailsList,omitempty"` 
	IsOperatedBySplitit bool `json:"IsOperatedBySplitit,omitempty"` 
	IsFundingBySplitit bool `json:"IsFundingBySplitit"` 
	DeductRevenueShareAutomaticallyFromLastInstallment bool `json:"DeductRevenueShareAutomaticallyFromLastInstallment"` 
	FundFirstInstallment bool `json:"FundFirstInstallment"` 
	TotalFundsCurrency *Currencies `json:"TotalFundsCurrency,omitempty"` 
	ParameterGroup *ParameterGroups `json:"ParameterGroup,omitempty"` 
	ScpProvidersCurrencies []ScpProvidersCurrencies `json:"ScpProvidersCurrencies,omitempty"` 
}
