/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// AccountUpdaterPendingCardsAllOf struct for AccountUpdaterPendingCardsAllOf
type AccountUpdaterPendingCardsAllOf struct {
	CardId int64 `json:"CardId"` 
	ExportTime *SplititTime `json:"ExportTime,omitempty"` 
	ExportBatchId string `json:"ExportBatchId,omitempty"` 
	ExportRecordId string `json:"ExportRecordId,omitempty"` 
	ImportTime *SplititTime `json:"ImportTime,omitempty"` 
	Card *Cards `json:"Card,omitempty"` 
	AccountUpdater AccountUpdaterProvider `json:"AccountUpdater"` 
}
