/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TestModes 
type TestModes string

// List of TestModes
const (
	TESTMODES_NONE TestModes = "None"
	TESTMODES_REGULAR TestModes = "Regular"
	TESTMODES_FAST TestModes = "Fast"
)
