/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// DelayResolution 
type DelayResolution string

// List of DelayResolution
const (
	DELAYRESOLUTION_UNKNOWN DelayResolution = "Unknown"
	DELAYRESOLUTION_PENDING_TECHNICAL_VERIFICATION DelayResolution = "PendingTechnicalVerification"
	DELAYRESOLUTION_PENDING_BANK_TRANSFER_CONFIRMATION DelayResolution = "PendingBankTransferConfirmation"
	DELAYRESOLUTION_PENDING_MID_ISSUE_RESOLUTION DelayResolution = "PendingMidIssueResolution"
	DELAYRESOLUTION_PENDING_SUSPICIOUS_REVIEW DelayResolution = "PendingSuspiciousReview"
	DELAYRESOLUTION_DEFAULTED_IN_COLLECTION DelayResolution = "DefaultedInCollection"
	DELAYRESOLUTION_DEFAULTED_PERMANENTLY DelayResolution = "DefaultedPermanently"
	DELAYRESOLUTION_DEFAULTED_COLLECTED_FROM_MERCHANT DelayResolution = "DefaultedCollectedFromMerchant"
)
