/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// InstallmentPlanSetupContexts struct for InstallmentPlanSetupContexts
type InstallmentPlanSetupContexts struct {
	Id int64 `json:"Id"` 
	PublicInstallmentPlanSession string `json:"PublicInstallmentPlanSession,omitempty"` 
	BillingAddressAddressLine string `json:"BillingAddressAddressLine,omitempty"` 
	BillingAddressZip string `json:"BillingAddressZip,omitempty"` 
	BillingAddressAddressLine2 string `json:"BillingAddressAddressLine2,omitempty"` 
	BillingAddressCity string `json:"BillingAddressCity,omitempty"` 
	RequestedNumberOfInstallments string `json:"RequestedNumberOfInstallments,omitempty"` 
	SuccessExitUrl string `json:"SuccessExitUrl,omitempty"` 
	ErrorExitUrl string `json:"ErrorExitUrl,omitempty"` 
	CancelExitUrl string `json:"CancelExitUrl,omitempty"` 
	AbTestQueryString string `json:"AbTestQueryString,omitempty"` 
	RequestedFirstInstallmentAmount float64 `json:"RequestedFirstInstallmentAmount"` 
	RequestedFirstScheduledInstallmentDate *SplititTime `json:"RequestedFirstScheduledInstallmentDate,omitempty"` 
	SendShopperApprovalRequest *SplititTime `json:"SendShopperApprovalRequest,omitempty"` 
	SendShopperPaymentRequest *SplititTime `json:"SendShopperPaymentRequest,omitempty"` 
	RequestedCaptureOnCreation bool `json:"RequestedCaptureOnCreation,omitempty"` 
	BillingAddressCountryId int64 `json:"BillingAddressCountryId,omitempty"` 
	SuggestedPaymentTPId int64 `json:"SuggestedPaymentTPId,omitempty"` 
	ABTestingSessionId int64 `json:"ABTestingSessionId,omitempty"` 
	DefaultNumOfInstallments int32 `json:"DefaultNumOfInstallments"` 
	BillingAddressStateId int64 `json:"BillingAddressStateId,omitempty"` 
	BillingAddressLegacyFullAddressLine string `json:"BillingAddressLegacyFullAddressLine,omitempty"` 
	RequestedFunding bool `json:"RequestedFunding,omitempty"` 
	SuccessAsyncUrl string `json:"SuccessAsyncUrl,omitempty"` 
	Attempt3Dsecure bool `json:"Attempt3Dsecure,omitempty"` 
	ViewName string `json:"ViewName,omitempty"` 
	IsOpenedInIframe bool `json:"IsOpenedInIframe"` 
	Is3dSecureInPopup bool `json:"Is3dSecureInPopup,omitempty"` 
	ExternalAuthUniqueGatewayId string `json:"ExternalAuthUniqueGatewayId,omitempty"` 
	ExternalAmountDetails float64 `json:"ExternalAmountDetails"` 
	ExternalAuthDate *SplititTime `json:"ExternalAuthDate"` 
	ExternalAuthTransactionLog string `json:"ExternalAuthTransactionLog,omitempty"` 
	PaymentApprovalPhone string `json:"PaymentApprovalPhone,omitempty"` 
	PaymentApprovalEmail string `json:"PaymentApprovalEmail,omitempty"` 
	PaymentMessage string `json:"PaymentMessage,omitempty"` 
	TermsAndConditionsKey string `json:"TermsAndConditionsKey,omitempty"` 
	FingerPrintId string `json:"FingerPrintId,omitempty"` 
	RequestUpdateCardPhone string `json:"RequestUpdateCardPhone,omitempty"` 
	RequestUpdateCardEmail string `json:"RequestUpdateCardEmail,omitempty"` 
	RequestUpdateCardTime *SplititTime `json:"RequestUpdateCardTime,omitempty"` 
	BillingAddressFirstTimePopulatedBy string `json:"BillingAddressFirstTimePopulatedBy,omitempty"` 
	Country *Countries `json:"Country,omitempty"` 
	State *CountrySubdivisions `json:"State,omitempty"` 
	ABTestingSession *PaymentFormTpabTestingDefinition `json:"ABTestingSession,omitempty"` 
	SuggestedPaymentTP *VersionedTouchPoints `json:"SuggestedPaymentTP,omitempty"` 
	InstallmentPlans []InstallmentPlans `json:"InstallmentPlans,omitempty"` 
	RequestedStrategy PlanStrategy `json:"RequestedStrategy,omitempty"` 
	BillingAddress *AddressData2 `json:"BillingAddress,omitempty"` 
}
