/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ExtendedCurrencyAllOf struct for ExtendedCurrencyAllOf
type ExtendedCurrencyAllOf struct {
	DecimalPlaces int32 `json:"DecimalPlaces"` 
}
