/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// Get3DSecureParametersResponse struct for Get3DSecureParametersResponse
type Get3DSecureParametersResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	IssuerRedirectUrl string `json:"IssuerRedirectUrl,omitempty"` 
	PaReq string `json:"PaReq,omitempty"` 
	Md string `json:"Md,omitempty"` 
	TermUrl string `json:"TermUrl,omitempty"` 
	ThreeDSecureParams map[string]string `json:"ThreeDSecureParams,omitempty"` 
}
