/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// VerifyPaymentResponse struct for VerifyPaymentResponse
type VerifyPaymentResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	IsPaid bool `json:"IsPaid"` 
	OriginalAmountPaid float64 `json:"OriginalAmountPaid,omitempty"` 
}
