/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FundingTransferReason 
type FundingTransferReason string

// List of FundingTransferReason
const (
	FUNDINGTRANSFERREASON_NEW_PLAN FundingTransferReason = "NewPlan"
	FUNDINGTRANSFERREASON_INSTALLMENT_CHARGE FundingTransferReason = "InstallmentCharge"
	FUNDINGTRANSFERREASON_PLAN_CANCELLATION FundingTransferReason = "PlanCancellation"
)
