/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// BusinessUnitsAllOf struct for BusinessUnitsAllOf
type BusinessUnitsAllOf struct {
	Name string `json:"Name,omitempty"` 
	ParentId int64 `json:"ParentId,omitempty"` 
	ExternalId string `json:"ExternalId,omitempty"` 
	Parent *BusinessUnits `json:"Parent,omitempty"` 
}
