/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TransferDocumentsAllOf struct for TransferDocumentsAllOf
type TransferDocumentsAllOf struct {
	Amount float64 `json:"Amount"` 
	CurrencyId int64 `json:"CurrencyId"` 
	BusinessUnitId int64 `json:"BusinessUnitId"` 
	AchStatus int32 `json:"AchStatus"` 
	Currency *Currencies `json:"Currency,omitempty"` 
	TransferDocumentDetails []TransferDocumentDetails `json:"TransferDocumentDetails,omitempty"` 
}
