/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanQueryCriteria struct for InstallmentPlanQueryCriteria
type InstallmentPlanQueryCriteria struct {
	MerchantId int64 `json:"MerchantId"` 
	CurrencyId int64 `json:"CurrencyId"` 
	InstallmentPlanId int64 `json:"InstallmentPlanId"` 
	InstallmentPlanNumber string `json:"InstallmentPlanNumber,omitempty"` 
	RefOrderNumber string `json:"RefOrderNumber,omitempty"` 
	InstallmentPlanAmount float64 `json:"InstallmentPlanAmount"` 
	CardNumber string `json:"CardNumber,omitempty"` 
	ConsumerName string `json:"ConsumerName,omitempty"` 
	ConsumerEmail string `json:"ConsumerEmail,omitempty"` 
	CardHolder string `json:"CardHolder,omitempty"` 
	PisMemberId int64 `json:"PisMemberId"` 
	AnyFilter string `json:"AnyFilter,omitempty"` 
	Eula bool `json:"Eula"` 
	ShowChargebackPlans bool `json:"ShowChargebackPlans"` 
	IsInAutoRetry bool `json:"IsInAutoRetry,omitempty"` 
	Strategy PlanStrategy `json:"Strategy,omitempty"` 
	InitiatedStatuses *InstallmentPlanInitiatedStatuses `json:"InitiatedStatuses,omitempty"` 
	FraudCheckResult FraudCheckResult `json:"FraudCheckResult,omitempty"` 
	InstallmentsPlanStatuses []InstallmentPlanStatus `json:"InstallmentsPlanStatuses,omitempty"` 
	TestModes []TestModes `json:"TestModes,omitempty"` 
	DelayResolutions []DelayResolution `json:"DelayResolutions,omitempty"` 
	TransactionInformation *TransactionInfo `json:"TransactionInformation,omitempty"` 
	DateInfo *InstallmentPlanDateInfo `json:"DateInfo,omitempty"` 
}
