/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// PaymentFormMessageType 
type PaymentFormMessageType string

// List of PaymentFormMessageType
const (
	PAYMENTFORMMESSAGETYPE_GENERAL_NOTICE PaymentFormMessageType = "GeneralNotice"
	PAYMENTFORMMESSAGETYPE_MERCHANT_NOTICE PaymentFormMessageType = "MerchantNotice"
	PAYMENTFORMMESSAGETYPE_GENERAL_ERROR PaymentFormMessageType = "GeneralError"
	PAYMENTFORMMESSAGETYPE_FATAL_ERROR PaymentFormMessageType = "FatalError"
)
