/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TermsAndConditionsGetResponse struct for TermsAndConditionsGetResponse
type TermsAndConditionsGetResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"`
	TermsAndConditions *TermsAndConditions `json:"TermsAndConditions,omitempty"`
}
