/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// SplititJobDefinitionsAllOf struct for SplititJobDefinitionsAllOf
type SplititJobDefinitionsAllOf struct {
	Code string `json:"Code,omitempty"` 
	Name string `json:"Name,omitempty"` 
	ScopeCode string `json:"ScopeCode,omitempty"` 
	CronExpression string `json:"CronExpression,omitempty"` 
	ParameterGroupId int64 `json:"ParameterGroupId,omitempty"` 
	ParameterGroup *ParameterGroups `json:"ParameterGroup,omitempty"` 
	UserJobSubscriptions []UserJobSubscriptions `json:"UserJobSubscriptions,omitempty"` 
}
