/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ConfigValuesAllOf struct for ConfigValuesAllOf
type ConfigValuesAllOf struct {
	Value string `json:"Value,omitempty"` 
	ConfigKeyId int64 `json:"ConfigKeyId"` 
	TouchPointColorValuesId int64 `json:"TouchPointColorValuesId,omitempty"` 
	ConfigKey *ConfigKeys `json:"ConfigKey,omitempty"` 
	TouchPointColorValues *TouchPointColorValues `json:"TouchPointColorValues,omitempty"` 
}
