/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// LearnMoreDetailsResponse struct for LearnMoreDetailsResponse
type LearnMoreDetailsResponse struct {
	ResponseHeader *ResponseHeader `json:"ResponseHeader,omitempty"` 
	SupportsCreditCard bool `json:"SupportsCreditCard"` 
	SupportsDebitCard bool `json:"SupportsDebitCard"` 
	ShowSecureStrategyInfo bool `json:"ShowSecureStrategyInfo"` 
	ShowNonSecureStrategyInfo bool `json:"ShowNonSecureStrategyInfo"` 
	Total *MoneyWithCurrencyCode `json:"Total,omitempty"` 
	Installments []Installment `json:"Installments,omitempty"` 
	NumberOfInstallments int32 `json:"NumberOfInstallments"` 
}
