/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// InstallmentPlanAuditLogs struct for InstallmentPlanAuditLogs
type InstallmentPlanAuditLogs struct {
	Id int64 `json:"Id"` 
	ActivityExecutionDate *SplititTime `json:"ActivityExecutionDate"` 
	UserId int64 `json:"UserId,omitempty"` 
	UserUniqueId string `json:"UserUniqueId,omitempty"` 
	BusinessActivity BusinessActivity `json:"BusinessActivity"` 
	TraceId string `json:"TraceId,omitempty"` 
	Result bool `json:"Result"` 
	VersionedTouchPoint *VersionedTouchPoints `json:"VersionedTouchPoint,omitempty"` 
	VersionedTouchPointId int64 `json:"VersionedTouchPointId,omitempty"` 
	Discriminator string `json:"Discriminator,omitempty"` 
	AdditionalInfo string `json:"AdditionalInfo,omitempty"` 
	UserType UserType `json:"UserType,omitempty"` 
	InstallmentPlanId int64 `json:"InstallmentPlanId,omitempty"` 
	CreatingIPAddress string `json:"CreatingIPAddress,omitempty"` 
	CardId int64 `json:"CardId,omitempty"` 
	Card *Cards `json:"Card,omitempty"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
	ErrorCode PisErrorCodes `json:"ErrorCode,omitempty"` 
}
