/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// CartData struct for CartData
type CartData struct {
	Items *[]ItemData `json:"Items,omitempty"`
	AmountDetails *AmountDetails `json:"AmountDetails,omitempty"`
}
