/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TransactionStatus 
type TransactionStatus string

// List of TransactionStatus
const (
	TRANSACTIONSTATUS_PENDING TransactionStatus = "Pending"
	TRANSACTIONSTATUS_FINISHED_SUCCESSFULLY TransactionStatus = "FinishedSuccessfully"
	TRANSACTIONSTATUS_FAILED TransactionStatus = "Failed"
	TRANSACTIONSTATUS_ALL_STATUSES TransactionStatus = "AllStatuses"
)
