/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// LoginRequest struct for LoginRequest
type LoginRequest struct {
	UserName string `json:"UserName,omitempty"` 
	Password string `json:"Password,omitempty"` 
	TouchPoint *TouchPoint `json:"TouchPoint,omitempty"` 
}
