/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// MoneyFlows 
type MoneyFlows string

// List of MoneyFlows
const (
	MONEYFLOWS_NOT_DETERMINED MoneyFlows = "NotDetermined"
	MONEYFLOWS_MONTHLY MoneyFlows = "Monthly"
	MONEYFLOWS_SCP MoneyFlows = "SCP"
	MONEYFLOWS_CUSTOM MoneyFlows = "Custom"
	MONEYFLOWS_PENDING_FUNDING MoneyFlows = "PendingFunding"
	MONEYFLOWS_CHOOSE MoneyFlows = "Choose"
)
