/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// GetInstallmentsPlanSearchCriteriaRequest struct for GetInstallmentsPlanSearchCriteriaRequest
type GetInstallmentsPlanSearchCriteriaRequest struct {
	QueryCriteria *InstallmentPlanQueryCriteria `json:"QueryCriteria,omitempty"`
	LoadRelated *RelationsLoad `json:"LoadRelated,omitempty"`
	PagingRequest *PagingRequestHeader `json:"PagingRequest,omitempty"`
}
