/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// ResponseError struct for ResponseError
type ResponseError struct {
	ErrorCode string `json:"ErrorCode,omitempty"`
	FieldName string `json:"FieldName,omitempty"`
	Message string `json:"Message,omitempty"`
}
