/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// BusinessParty 
type BusinessParty string

// List of BusinessParty
const (
	BUSINESSPARTY_SPLITIT BusinessParty = "Splitit"
	BUSINESSPARTY_AGENTS BusinessParty = "Agents"
	BUSINESSPARTY_MERCHANTS BusinessParty = "Merchants"
	BUSINESSPARTY_CONSUMERS BusinessParty = "Consumers"
)
