/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// AmountDetails struct for AmountDetails
type AmountDetails struct {
	SubTotal float64 `json:"SubTotal"` 
	Tax float64 `json:"Tax"` 
	Shipping float64 `json:"Shipping"` 
}
