/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// TerminalGatewayDatas struct for TerminalGatewayDatas
type TerminalGatewayDatas struct {
	Id int64 `json:"Id"` 
	Token string `json:"Token,omitempty"` 
	IsActive bool `json:"IsActive"` 
	NumberOfAllowedDaysForRefund int32 `json:"NumberOfAllowedDaysForRefund"` 
	ProcessorId int64 `json:"ProcessorId,omitempty"` 
	TerminalId int64 `json:"TerminalId,omitempty"` 
	IsAddressRequires bool `json:"IsAddressRequires"` 
	Processor *Processors `json:"Processor,omitempty"` 
	Terminal *Terminals `json:"Terminal,omitempty"` 
	PaymentGatewayTransactionLogs []PaymentGatewayTransactionLogs `json:"PaymentGatewayTransactionLogs,omitempty"` 
	AuthenticationValues map[string]string `json:"AuthenticationValues,omitempty"` 
	AuthenticationValuesAsXml string `json:"AuthenticationValuesAsXml,omitempty"` 
}
