/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
import (
	
)
// InstallmentsAllOf struct for InstallmentsAllOf
type InstallmentsAllOf struct {
	InstallmentPlanId int64 `json:"InstallmentPlanId"` 
	InstallmentNumber int64 `json:"InstallmentNumber"` 
	ProcessorId int64 `json:"ProcessorId"` 
	OriginUtcOffset float64 `json:"OriginUtcOffset"` 
	CreatedDateUtc *SplititTime `json:"CreatedDateUtc"` 
	Amount float64 `json:"Amount"` 
	ProcessDateTime *SplititTime `json:"ProcessDateTime,omitempty"` 
	ProcessDateTimeUtc *SplititTime `json:"ProcessDateTimeUtc,omitempty"` 
	IsRefund bool `json:"IsRefund"` 
	CardStateId int64 `json:"CardStateId,omitempty"` 
	OriginalAmount float64 `json:"OriginalAmount"` 
	RefundAmount float64 `json:"RefundAmount"` 
	IsFullCapture bool `json:"IsFullCapture"` 
	AuthorizedAmount float64 `json:"AuthorizedAmount"` 
	IsPreAuthorized bool `json:"IsPreAuthorized"` 
	AmountForFunding float64 `json:"AmountForFunding"` 
	CardState *CardStateLogs `json:"CardState,omitempty"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
	Processor *Processors `json:"Processor,omitempty"` 
	FeesDocuments []FeesDocuments `json:"FeesDocuments,omitempty"` 
	FundingCollectDocumentDetails []FundingCollectDocumentDetails `json:"FundingCollectDocumentDetails,omitempty"` 
	InstallmentPaymentGatewayTransactionLogs []InstallmentPaymentGatewayTransactionLogs `json:"InstallmentPaymentGatewayTransactionLogs,omitempty"` 
	TransferDocumentDetails []TransferDocumentDetails `json:"TransferDocumentDetails,omitempty"` 
	MerchantAccountType MerchantAccountType `json:"MerchantAccountType"` 
	Status InstallmentStatus `json:"Status"` 
}
