/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FailureUnderFrozenInstallmentsPlan 
type FailureUnderFrozenInstallmentsPlan string

// List of FailureUnderFrozenInstallmentsPlan
const (
	FAILUREUNDERFROZENINSTALLMENTSPLAN_NONE FailureUnderFrozenInstallmentsPlan = "None"
	FAILUREUNDERFROZENINSTALLMENTSPLAN_CANCEL_INSTALLMENTS_PLAN FailureUnderFrozenInstallmentsPlan = "CancelInstallmentsPlan"
	FAILUREUNDERFROZENINSTALLMENTSPLAN_PERFORM_FULL_CAPTURE FailureUnderFrozenInstallmentsPlan = "PerformFullCapture"
	FAILUREUNDERFROZENINSTALLMENTSPLAN_CHOOSE FailureUnderFrozenInstallmentsPlan = "Choose"
)
