/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// FeesRuleDatasAllOf struct for FeesRuleDatasAllOf
type FeesRuleDatasAllOf struct {
	AccountingCurrencyId int64 `json:"AccountingCurrencyId"` 
	AccountingCurrency *Currencies `json:"AccountingCurrency,omitempty"` 
	BusinessUnitId int64 `json:"BusinessUnitId"` 
	BusinessUnit *BusinessUnits `json:"BusinessUnit,omitempty"` 
	PosSetupPercentage float64 `json:"PosSetupPercentage"` 
	RefundFee float64 `json:"RefundFee"` 
	CancellationFee float64 `json:"CancellationFee"` 
	ChbFee float64 `json:"ChbFee"` 
	MonthlySubscriptionAmount float64 `json:"MonthlySubscriptionAmount"` 
	FraudCheck float64 `json:"FraudCheck"` 
	FixedNonFundedSecure *FeeRateCollections `json:"FixedNonFundedSecure,omitempty"` 
	VariableNonFundedSecure *FeeRateCollections `json:"VariableNonFundedSecure,omitempty"` 
	FixedNonFundedNonSecure *FeeRateCollections `json:"FixedNonFundedNonSecure,omitempty"` 
	VariableNonFundedNonSecure *FeeRateCollections `json:"VariableNonFundedNonSecure,omitempty"` 
	FixedFundedSecure *FeeRateCollections `json:"FixedFundedSecure,omitempty"` 
	FixedFundedNonSecure *FeeRateCollections `json:"FixedFundedNonSecure,omitempty"` 
	VariableFundedSecure *FeeRateCollections `json:"VariableFundedSecure,omitempty"` 
	VariableFundedNonSecure *FeeRateCollections `json:"VariableFundedNonSecure,omitempty"` 
	VariableFundedNonSecureId int64 `json:"VariableFundedNonSecureId,omitempty"` 
	VariableFundedSecureId int64 `json:"VariableFundedSecureId,omitempty"` 
	VariableNonFundedNonSecureId int64 `json:"VariableNonFundedNonSecureId,omitempty"` 
	VariableNonFundedSecureId int64 `json:"VariableNonFundedSecureId,omitempty"` 
	FixedFundedNonSecureId int64 `json:"FixedFundedNonSecureId,omitempty"` 
	FixedFundedSecureId int64 `json:"FixedFundedSecureId,omitempty"` 
	FixedNonFundedNonSecureId int64 `json:"FixedNonFundedNonSecureId,omitempty"` 
	FixedNonFundedSecureId int64 `json:"FixedNonFundedSecureId,omitempty"` 
	InstallmentPlanTerminalDatas []InstallmentPlanTerminalDatas `json:"InstallmentPlanTerminalDatas,omitempty"` 
}
