/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// SplititEntity 
type SplititEntity string

// List of SplititEntity
const (
	SPLITITENTITY_NOT_SET SplititEntity = "NotSet"
	SPLITITENTITY_SPLITIT_LTD SplititEntity = "SplititLtd"
	SPLITITENTITY_SPLITIT_UK_LTD SplititEntity = "SplititUkLtd"
	SPLITITENTITY_SPLITIT_USA_INC SplititEntity = "SplititUsaInc"
	SPLITITENTITY_SPLITIT_CAPITAL_INC SplititEntity = "SplititCapitalInc"
	SPLITITENTITY_SPLITIT_CAPITAL_UK_LTD SplititEntity = "SplititCapitalUkLtd"
	SPLITITENTITY_SPLITIT_PAYMENTS_LTD SplititEntity = "SplititPaymentsLtd"
	SPLITITENTITY_SPLITIT_AUSTRALIA_CAPITAL_PTY_LTD SplititEntity = "SplititAustraliaCapitalPtyLtd"
	SPLITITENTITY_SPLITIT_AUSTRALIA_PTY_LTD SplititEntity = "SplititAustraliaPtyLtd"
)
