/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanTerminalDatasAllOf struct for InstallmentPlanTerminalDatasAllOf
type InstallmentPlanTerminalDatasAllOf struct {
	ScpVariableCostAnnualPercent float64 `json:"ScpVariableCostAnnualPercent"` 
	ScpFundingPercent float64 `json:"ScpFundingPercent"` 
	ScpReservePoolPercent float64 `json:"ScpReservePoolPercent"` 
	ScpReturnMerchantMaxDays int32 `json:"ScpReturnMerchantMaxDays"` 
	ScpRevenueSharePercent float64 `json:"ScpRevenueSharePercent"` 
	ScpFixedCost float64 `json:"ScpFixedCost"` 
	AccountingCurrencyId int64 `json:"AccountingCurrencyId,omitempty"` 
	FundingRuleScpSettingId int64 `json:"FundingRuleScpSettingId,omitempty"` 
	FeesRuleDataId int64 `json:"FeesRuleDataId,omitempty"` 
	AccountingCurrency *Currencies `json:"AccountingCurrency,omitempty"` 
	FeesRuleData *FeesRuleDatas `json:"FeesRuleData,omitempty"` 
	FundingRuleScpSetting *FundingRuleDataScpProviderSetting `json:"FundingRuleScpSetting,omitempty"` 
	InstallmentPlans []InstallmentPlans `json:"InstallmentPlans,omitempty"` 
}
