/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// UserType 
type UserType string

// List of UserType
const (
	USERTYPE_USER UserType = "User"
	USERTYPE_APPLICATIVE_USER UserType = "ApplicativeUser"
	USERTYPE_USER_WITH_ACTION_ITEM UserType = "UserWithActionItem"
	USERTYPE_ADMIN_USER UserType = "AdminUser"
	USERTYPE_PIS_USER UserType = "PisUser"
	USERTYPE_API_USER UserType = "ApiUser"
	USERTYPE_PIS_MEMBER UserType = "PisMember"
)
