/*
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package splitit
// InstallmentPlanAuditLogsAllOf struct for InstallmentPlanAuditLogsAllOf
type InstallmentPlanAuditLogsAllOf struct {
	InstallmentPlanId int64 `json:"InstallmentPlanId,omitempty"` 
	CreatingIPAddress string `json:"CreatingIPAddress,omitempty"` 
	CardId int64 `json:"CardId,omitempty"` 
	Card *Cards `json:"Card,omitempty"` 
	InstallmentPlan *InstallmentPlans `json:"InstallmentPlan,omitempty"` 
	ErrorCode PisErrorCodes `json:"ErrorCode,omitempty"` 
}
